In [1]:
import pandas as pd

In [2]:
pd.options.display.max_columns = 500

In [3]:
account_history = pd.read_csv('../vol/web/media/insumos/automatic/ACCOUNT_HISTORY.txt', sep='~', low_memory=False)

In [4]:
account_history.head()

,BankId,AppId,Acct,RecordDate,TypeId,TotalBalance,PrincipalBalance,InterestBalance,AverageBalance,Rate,DaysPastDue,InterestMTD,NumPmtsPastDue,Num30DPD,Amt30DPD,Num60DPD,Amt60DPD,Num90DPD,Amt90DPD,Num120DPD,Amt120DPD,Num150DPD,Amt150DPD,Num180DPD,Amt180DPD,Num210DPD,Amt210DPD,IntAccruedToDate,AmountPmtPastDue,TotalPrinPastDue,MinBalance,IntAccruedMTD,NumDaysOverdrawn,PrimeRateNum,LateFees,PastDueDate1,PastDueDate2,PastDueInt1,PastDueInt2,PastDuePrin1,PastDuePrin2,LastRcvdPmtDate,BlockCode1Date,BlockCodeId1,BlockReason1,BlockCode2Date,BlockCodeId2,BlockReason2,StatusId,CreditLimit,CashBalance,HDelinquency,CurrentAmtDue,ChargeOffStatusId,CurrencyId,LastPmtAmount,BucketReal,Gold,Opened,ActiveInvoluntary,Transactor,OpenedThisMonth,UpgradedThisMonth,NRFF,PFTR,Profitability,BehaviorScore,MOB,NRFF2,LoanStatus,LoanTermStatus,LoanCondition,PCTID,BranchId,OfficerId,MaturityDate,TermDays,ExpirationDate,OpenDate,CancelDate,CapitalCastigado,SaldoCastigado,MontoRecuperado,CurrBillPrin,CurrBillInt,CurrBillDueDate,MtdAvgBal,ChargeOffDate,CurrPmtType,PrinTranAddr,AmtTranDDR,NextSchedBill,ANR,RISK,Rate_Formateada
0,51,20,1000632011,2019-07-31 00:00:00,2,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,512.0,NaN,?,?,?,NaN,2.0,EL,NaN,0.0,NaN,1959-02-04 00:00:00,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
1,51,20,1000785012,2019-07-31 00:00:00,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,121.0,NaN,?,?,?,NaN,2.0,EL,NaN,0.0,NaN,1991-09-30 00:00:00,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
2,51,20,1001086029,2019-07-31 00:00:00,2,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,627.0,NaN,?,?,?,NaN,3.0,AR,NaN,0.0,NaN,1952-01-15 00:00:00,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
3,51,20,1001610011,2019-07-31 00:00:00,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000011111...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,296.0,NaN,?,?,?,NaN,3.0,AR,NaN,0.0,NaN,1991-07-01 00:00:00,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
4,51,20,1001944017,2019-07-31 00:00:00,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,121.0,NaN,?,?,?,NaN,2.0,EL,NaN,0.0,NaN,1991-09-30 00:00:00,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0

In [5]:
account_history.tail()

,BankId,AppId,Acct,RecordDate,TypeId,TotalBalance,PrincipalBalance,InterestBalance,AverageBalance,Rate,DaysPastDue,InterestMTD,NumPmtsPastDue,Num30DPD,Amt30DPD,Num60DPD,Amt60DPD,Num90DPD,Amt90DPD,Num120DPD,Amt120DPD,Num150DPD,Amt150DPD,Num180DPD,Amt180DPD,Num210DPD,Amt210DPD,IntAccruedToDate,AmountPmtPastDue,TotalPrinPastDue,MinBalance,IntAccruedMTD,NumDaysOverdrawn,PrimeRateNum,LateFees,PastDueDate1,PastDueDate2,PastDueInt1,PastDueInt2,PastDuePrin1,PastDuePrin2,LastRcvdPmtDate,BlockCode1Date,BlockCodeId1,BlockReason1,BlockCode2Date,BlockCodeId2,BlockReason2,StatusId,CreditLimit,CashBalance,HDelinquency,CurrentAmtDue,ChargeOffStatusId,CurrencyId,LastPmtAmount,BucketReal,Gold,Opened,ActiveInvoluntary,Transactor,OpenedThisMonth,UpgradedThisMonth,NRFF,PFTR,Profitability,BehaviorScore,MOB,NRFF2,LoanStatus,LoanTermStatus,LoanCondition,PCTID,BranchId,OfficerId,MaturityDate,TermDays,ExpirationDate,OpenDate,CancelDate,CapitalCastigado,SaldoCastigado,MontoRecuperado,CurrBillPrin,CurrBillInt,CurrBillDueDate,MtdAvgBal,ChargeOffDate,CurrPmtType,PrinTranAddr,AmtTranDDR,NextSchedBill,ANR,RISK,Rate_Formateada
639651,51,50,5549290000509079,2019-07-31 00:00:00,999,0.0,0.0,0.0,0.0,NaN,0,NaN,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2018-03-28 00:00:00,2018-08-31 00:00:00,B,05,2018-08-21 00:00:00,,,11,0.0,0.0,000000000002100011111212,0.0,NaN,0,0.36,0,0,0,1,1,0,0,0.0,0.0,0.0,0.0,160.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2022-04-30 00:00:00,2005-04-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
639652,51,50,5549290000509145,2019-07-31 00:00:00,999,0.0,0.0,0.0,0.0,NaN,0,NaN,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-12 00:00:00,2018-01-16 00:00:00,X,02,2017-10-23 00:00:00,,,11,1.0,0.0,000000000000000000001211,0.0,NaN,0,0.05,0,0,0,1,1,0,0,0.0,0.0,0.0,9.0,235.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2018-03-31 00:00:00,1998-05-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
639653,51,50,5549290000509442,2019-07-31 00:00:00,999,0.0,0.0,0.0,0.0,NaN,0,NaN,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-20 00:00:00,2019-02-18 00:00:00,B,05,2016-10-05 00:00:00,,,11,7.0,0.0,000000000000000000001000,0.0,NaN,0,2.32,0,0,0,1,1,0,0,0.0,0.0,0.0,9.0,212.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2021-12-31 00:00:00,2001-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
639654,51,50,5549290000509566,2019-07-31 00:00:00,999,0.0,0.0,0.0,0.0,NaN,0,NaN,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-23 00:00:00,2016-08-31 00:00:00,U,,2014-03-10 00:00:00,,,13,0.0,0.0,000000000000000000000000,0.0,NaN,0,0.00,0,0,0,0,1,0,0,0.0,0.0,0.0,0.0,38.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2017-06-30 00:00:00,2013-06-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
639655,51,50,5549290000509889,2019-07-31 00:00:00,999,0.0,0.0,0.0,0.0,NaN,0,NaN,0.0,1,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-07 00:00:00,2018-05-08 00:00:00,B,05,2016-11-10 00:00:00,,,11,0.0,0.0,000000000000000000001111,0.0,NaN,0,0.01,0,0,0,1,1,0,0,0.0,0.0,0.0,0.0,203.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2022-06-30 00:00:00,2001-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

In [6]:
account_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639656 entries, 0 to 639655
Data columns (total 95 columns):
BankId               639656 non-null int64
AppId                639656 non-null int64
Acct                 639656 non-null int64
RecordDate           639656 non-null object
TypeId               639656 non-null int64
TotalBalance         639656 non-null float64
PrincipalBalance     639656 non-null float64
InterestBalance      639656 non-null float64
AverageBalance       639656 non-null float64
Rate                 530881 non-null float64
DaysPastDue          639656 non-null int64
InterestMTD          467228 non-null float64
NumPmtsPastDue       639656 non-null float64
Num30DPD             639656 non-null int64
Amt30DPD             108775 non-null float64
Num60DPD             639656 non-null int64
Amt60DPD             108775 non-null float64
Num90DPD             639656 non-null int64
Amt90DPD             108775 non-null float64
Num120DPD            108775 non-null float64
Amt120DPD            108775 non-null float64
Num150DPD            108775 non-null float64
Amt150DPD            108775 non-null float64
Num180DPD            108775 non-null float64
Amt180DPD            108775 non-null float64
Num210DPD            108775 non-null float64
Amt210DPD            108775 non-null float64
IntAccruedToDate     530881 non-null float64
AmountPmtPastDue     639656 non-null float64
TotalPrinPastDue     530881 non-null float64
MinBalance           530881 non-null float64
IntAccruedMTD        539986 non-null float64
NumDaysOverdrawn     530881 non-null float64
PrimeRateNum         530881 non-null float64
LateFees             639656 non-null float64
PastDueDate1         1922 non-null object
PastDueDate2         1427 non-null object
PastDueInt1          530881 non-null float64
PastDueInt2          530881 non-null float64
PastDuePrin1         530881 non-null float64
PastDuePrin2         530881 non-null float64
LastRcvdPmtDate      307976 non-null object
BlockCode1Date       107768 non-null object
BlockCodeId1         108775 non-null object
BlockReason1         108775 non-null object
BlockCode2Date       90058 non-null object
BlockCodeId2         108775 non-null object
BlockReason2         108775 non-null object
StatusId             639656 non-null int64
CreditLimit          639656 non-null float64
CashBalance          108775 non-null float64
HDelinquency         566898 non-null object
CurrentAmtDue        108775 non-null float64
ChargeOffStatusId    0 non-null float64
CurrencyId           639656 non-null int64
LastPmtAmount        108775 non-null float64
BucketReal           639656 non-null int64
Gold                 639656 non-null int64
Opened               639656 non-null int64
ActiveInvoluntary    639656 non-null int64
Transactor           639656 non-null int64
OpenedThisMonth      639656 non-null int64
UpgradedThisMonth    639656 non-null int64
NRFF                 639656 non-null float64
PFTR                 639656 non-null float64
Profitability        639656 non-null float64
BehaviorScore        108775 non-null float64
MOB                  639651 non-null float64
NRFF2                0 non-null float64
LoanStatus           530881 non-null object
LoanTermStatus       530881 non-null object
LoanCondition        530881 non-null object
PCTID                108775 non-null float64
BranchId             530881 non-null float64
OfficerId            530881 non-null object
MaturityDate         135178 non-null object
TermDays             530881 non-null float64
ExpirationDate       108775 non-null object
OpenDate             639651 non-null object
CancelDate           6049 non-null object
CapitalCastigado     530881 non-null float64
SaldoCastigado       530881 non-null float64
MontoRecuperado      530881 non-null float64
CurrBillPrin         530881 non-null float64
CurrBillInt          530881 non-null float64
CurrBillDueDate      2606 non-null object
MtdAvgBal            530881 non-null float64
ChargeOffDate        0 non-null float64
CurrPmtType          139014 non-null float64
PrinTranAddr         530881 non-null float64
AmtTranDDR           530881 non-null float64
NextSchedBill        185307 non-null object
ANR                  1217 non-null float64
RISK                 639656 non-null int64
Rate_Formateada      530881 non-null float64
dtypes: float64(56), int64(18), object(21)
memory usage: 463.6+ MB

In [7]:
account_history.describe()

,BankId,AppId,Acct,TypeId,TotalBalance,PrincipalBalance,InterestBalance,AverageBalance,Rate,DaysPastDue,InterestMTD,NumPmtsPastDue,Num30DPD,Amt30DPD,Num60DPD,Amt60DPD,Num90DPD,Amt90DPD,Num120DPD,Amt120DPD,Num150DPD,Amt150DPD,Num180DPD,Amt180DPD,Num210DPD,Amt210DPD,IntAccruedToDate,AmountPmtPastDue,TotalPrinPastDue,MinBalance,IntAccruedMTD,NumDaysOverdrawn,PrimeRateNum,LateFees,PastDueInt1,PastDueInt2,PastDuePrin1,PastDuePrin2,StatusId,CreditLimit,CashBalance,CurrentAmtDue,ChargeOffStatusId,CurrencyId,LastPmtAmount,BucketReal,Gold,Opened,ActiveInvoluntary,Transactor,OpenedThisMonth,UpgradedThisMonth,NRFF,PFTR,Profitability,BehaviorScore,MOB,NRFF2,PCTID,BranchId,TermDays,CapitalCastigado,SaldoCastigado,MontoRecuperado,CurrBillPrin,CurrBillInt,MtdAvgBal,ChargeOffDate,CurrPmtType,PrinTranAddr,AmtTranDDR,ANR,RISK,Rate_Formateada
count,639656.000000,639656.000000,6.396560e+05,639656.000000,6.396560e+05,6.396560e+05,639656.000000,6.396560e+05,530881.000000,639656.000000,467228.000000,639656.000000,639656.000000,108775.000000,639656.000000,108775.000000,639656.000000,108775.000000,108775.000000,108775.000000,108775.000000,108775.000000,108775.000000,108775.000000,108775.000000,1.087750e+05,530881.000000,639656.000000,530881.000000,5.308810e+05,539986.000000,530881.00000,530881.000000,639656.000000,530881.000000,530881.000000,530881.000000,530881.000000,639656.000000,6.396560e+05,108775.000000,108775.000000,0.0,639656.000000,108775.000000,639656.000000,639656.000000,639656.000000,639656.000000,639656.000000,639656.000000,639656.0,639656.0,639656.0,639656.0,108775.000000,639651.000000,0.0,108775.000000,530881.000000,530881.000000,530881.000000,530881.000000,530881.000000,530881.000000,530881.000000,5.308810e+05,0.0,139014.000000,5.308810e+05,5.308810e+05,1217.000000,639656.000000,530881.000000
mean,51.008442,35.809357,8.464605e+14,399.648034,1.592820e+03,1.589240e+03,3.579817,1.359093e+03,0.181692,2.540914,11.874632,0.039645,1.223938,0.004845,0.501104,0.000313,0.328320,0.000294,0.399926,0.000290,0.231937,0.000341,0.086913,0.000300,0.000662,1.838658e-07,6.726761,0.113592,0.000614,1.385602e+03,13.058098,0.01777,4.689239,0.000002,0.000015,0.000009,0.000033,0.000016,6.504829,8.915044e+02,84.144480,19.775524,NaN,0.008442,440.608548,0.082582,0.105466,0.028676,0.260671,0.999226,-0.009855,0.0,0.0,0.0,0.0,18.733983,87.573345,NaN,5.273932,3.478329,4.725729,0.002557,0.001854,0.000708,1.892723,3.696464,2.053320e+02,NaN,6.310055,2.849038e+04,3.154975e+04,150595.681264,0.619941,0.181692
std,0.091492,14.369381,1.880824e+15,350.123503,1.181673e+05,1.177507e+05,789.616865,9.317805e+04,0.221200,38.437694,1298.270766,0.474749,3.059359,1.474589,1.492150,0.008645,1.064541,0.004370,1.152814,0.003617,0.790440,0.003885,0.281840,0.003887,0.102820,4.287938e-05,1861.879770,55.945197,0.128908,1.103522e+05,755.190116,3.30791,13.575655,0.000598,0.002217,0.001688,0.002339,0.001692,3.105207,6.657886e+04,3834.736378,755.216686,NaN,0.091492,13009.614820,0.687969,0.307153,0.166895,0.439001,0.027807,0.098863,0.0,0.0,0.0,0.0,107.742911,71.249997,NaN,6.104952,1.465628,16.341691,0.073455,0.064282,0.035484,626.177677,1234.782915,6.847392e+04,NaN,1.930426,5.762548e+05,6.074375e+05,245424.645212,2.166408,0.221200
min,51.000000,20.000000,1.000000e+00,1.000000,-6.919996e+04,-6.919996e+04,-0.410000,-1.935410e+03,-0.243833,0.000000,-0.050700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,-0.180000,0.000000,0.000000,-5.000000e+01,0.000000,0.00000,0.000000,-0.010000,-0.010000,0.000000,0.000000,0.000000,-1.000000,0.000000e+00,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.010000,-7.000000e-02,NaN,0.000000,-6.246140e+03,-2.623666e+05,0.000000,-1.000000,-0.243833
25%,51.000000,20.000000,1.033276e+09,28.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000e+00,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,37.000000,NaN,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,7.000000,0.000000e+00,0.000000e+00,0.000000,-1.000000,0.000000
50%,51.000000,30.000000,5.044209e+09,297.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000e+00,0.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,66.000000,NaN,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,7.000000,0.000000e+00,0.000000e+00,0.654200,-1.000000,0.000000
75%,51.000000,50.000000,7.060438e+09,597.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.390000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.00000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,0.000000e+00,0.000000,0.000000,NaN,0.000000,0.010000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.0,0.0,0.0,0.0,5.000000,117.000000,NaN,11.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,NaN,7.000000,0.000000e+00,0.000000e+00,216095.070000,2.000000,0.390000
max,52.000000,50.000000,5.549290e+15,999.000000,6.301787e+07,6.301787e+07,335416.670000,5.972819e+07,7.500000,999.000000,449296.936800,8.000000,60.000000,486.320000,106.000000,2.430000,35.000000,0.800000,26.000000,0.340000,16.000000,0.340000,2.000000,0.480000,23.000000,1.000000e-02,755268.297100,41447.590000,54.640000,6.301787e+07,367807.320000,979.00000,99.000000,0.240000,0.760000,0.750000,0.590000,0.590000,14.000000,2.500000e+07,357830.430000,53969.440000,NaN,1.000000,779267.480000,9.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,762.000000,818.000000,NaN,55.000000,11.000000,982.000000,23.880000,23.880000,7.990000,228569.570000,452083.330000,2.500000e+07,NaN,8.000000,2.263526e+08,2.263526e+08,867848.155700,6.000000,7.500000

In [8]:
account_history.loc[account_history.PrincipalBalance.sort_values(ascending=False).index]

,BankId,AppId,Acct,RecordDate,TypeId,TotalBalance,PrincipalBalance,InterestBalance,AverageBalance,Rate,DaysPastDue,InterestMTD,NumPmtsPastDue,Num30DPD,Amt30DPD,Num60DPD,Amt60DPD,Num90DPD,Amt90DPD,Num120DPD,Amt120DPD,Num150DPD,Amt150DPD,Num180DPD,Amt180DPD,Num210DPD,Amt210DPD,IntAccruedToDate,AmountPmtPastDue,TotalPrinPastDue,MinBalance,IntAccruedMTD,NumDaysOverdrawn,PrimeRateNum,LateFees,PastDueDate1,PastDueDate2,PastDueInt1,PastDueInt2,PastDuePrin1,PastDuePrin2,LastRcvdPmtDate,BlockCode1Date,BlockCodeId1,BlockReason1,BlockCode2Date,BlockCodeId2,BlockReason2,StatusId,CreditLimit,CashBalance,HDelinquency,CurrentAmtDue,ChargeOffStatusId,CurrencyId,LastPmtAmount,BucketReal,Gold,Opened,ActiveInvoluntary,Transactor,OpenedThisMonth,UpgradedThisMonth,NRFF,PFTR,Profitability,BehaviorScore,MOB,NRFF2,LoanStatus,LoanTermStatus,LoanCondition,PCTID,BranchId,OfficerId,MaturityDate,TermDays,ExpirationDate,OpenDate,CancelDate,CapitalCastigado,SaldoCastigado,MontoRecuperado,CurrBillPrin,CurrBillInt,CurrBillDueDate,MtdAvgBal,ChargeOffDate,CurrPmtType,PrinTranAddr,AmtTranDDR,NextSchedBill,ANR,RISK,Rate_Formateada
38530,51,20,1035942005,2019-07-31 00:00:00,35,63017871.00,63017871.00,0.00,5.972819e+07,0.001,0,0.0000,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0,0.0,63017871.0,5143.25,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,NaN,1111111111111111111111111111111111111111111111...,NaN,NaN,0,NaN,1,1,1,1,1,0,0,0.0,0.0,0.0,NaN,238.0,NaN,?,?,?,NaN,3.0,ALU,NaN,0.0,NaN,1999-09-24 00:00:00,NaN,0.0,0.0,0.0,0.00,0.00,NaN,0.00,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.001
424010,51,50,9019869601,2019-07-31 00:00:00,17,25335416.66,25000000.00,335416.67,0.000000e+00,0.210,0,335416.6666,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,335416.6666,0.0,0.0,0.0,0.00,0.0,92.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,25000000.0,NaN,1,NaN,NaN,0,NaN,1,1,1,1,1,1,0,0.0,0.0,0.0,NaN,0.0,NaN,CUR,?,?,NaN,2.0,ABR,2024-07-09 00:00:00,0.0,NaN,2019-07-09 00:00:00,NaN,0.0,0.0,0.0,224250.64,452083.33,2019-08-09 00:00:00,25000000.00,NaN,8.0,0.0,0.0,2019-09-09 00:00:00,NaN,0,0.210
406782,51,50,9019869301,2019-07-31 00:00:00,17,25050046.30,24761166.03,288880.27,0.000000e+00,0.210,0,449296.9368,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,726380.2701,0.0,0.0,0.0,0.00,0.0,92.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,2019-07-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0,25000000.0,NaN,11,NaN,NaN,0,NaN,1,1,1,1,1,0,0,0.0,0.0,0.0,NaN,1.0,NaN,CUR,?,?,NaN,2.0,ABR,2024-06-12 00:00:00,0.0,NaN,2019-06-12 00:00:00,NaN,0.0,0.0,0.0,228569.57,447764.42,2019-08-12 00:00:00,24884435.17,NaN,8.0,0.0,0.0,2019-09-12 00:00:00,NaN,0,0.210
529846,51,50,9019869101,2019-07-31 00:00:00,17,25078934.32,24761166.03,317768.30,0.000000e+00,0.210,0,449018.2972,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,755268.2971,0.0,0.0,0.0,0.00,0.0,92.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,2019-07-10 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0,25000000.0,NaN,11,NaN,NaN,0,NaN,1,1,1,1,1,0,0,0.0,0.0,0.0,NaN,1.0,NaN,CUR,?,?,NaN,4.0,ARB,2024-06-10 00:00:00,0.0,NaN,2019-06-10 00:00:00,NaN,0.0,0.0,0.0,228569.57,447764.42,2019-08-10 00:00:00,24830504.92,NaN,8.0,0.0,0.0,2019-09-10 00:00:00,NaN,0,0.210
442976,51,50,9019869201,2019-07-31 00:00:00,17,25050046.30,24761166.03,288880.27,0.000000e+00,0.210,0,449296.9368,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,726380.2701,0.0,0.0,0.0,0.00,0.0,92.0,0.0,NaN,NaN,0.0,0.0,0.0,0.0,2019-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0,25000000.0,NaN,11,NaN,NaN,0,NaN,1,1,1,1,1,0,0,0.0,0.0,0.0,NaN,1.0,NaN,CUR,?,?,NaN,2.0,ABR,2024-06-12 00:00:00,0.0,NaN,2019-06-12 00:00:00,NaN,0.0,0.0,0.0,228569.57,447764.42,2019-08-12 00:00:00,24845913.56,NaN,8.0,0.0,0.0,2019-09-12 00:00:00,NaN,0,0.210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574802,51,50,5197230000461124,2019-07-31 00:00:00,999,-531.63,-531.63,0.00,0.000000e+00,NaN,0,0.0000,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.00,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2019-03-06 00:00:00,2017-12-05 00:00:00,,,2015-09-01 00:00:00,,,9,6750.0,0.0,000000000001111111111111,0.0,NaN,0,500.0,0,0,1,0,1,0,0,0.0,0.0,0.0,734.0,54.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2023-01-31 00:00:00,2015-01-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,1,NaN
573828,51,50,5197230000243597,2019-07-31 00:00:00,999,-572.97,-572.97,0.00,0.000000e+00,NaN,0,0.0000,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.00,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-09 00:00:00,2019-05-13 00:00:00,B,05,NaN,,,9,6750.0,0.0,000000000000000000000000,0.0,NaN,0,100.0,0,0,0,1,1,0,0,0.0,0.0,0.0,11.0,79.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2020-10-31 00:00:00,2012-10-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0,NaN
585490,51,50,5197230000324330,2019-07-31 00:00:00,999,-573.50,-573.50,0.00,6.164851e+02,NaN,0,39.3900,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,39.39,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-26 00:00:00,2017-09-22 00:00:00,,,2018-09-17 00:00:00,,,9,6750.0,0.0,111111110001211111111111,0.0,NaN,0,1000.0,0,0,1,1,0,0,0,0.0,0.0,0.0,737.0,83.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2020-08-31 00:00:00,2012-08-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1266.2678,1,NaN
599857,51,50,5464900000891019,2019-07-31 00:00:00,999,-1716.03,-1716.03,0.00,0.000000e+00,NaN,0,0.0000,0.0,5,0.0,2,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.00,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-25 00:00:00,2014-01-07 00:00:00,,,2018-07-16 00:00:00,,,9,775000.0,0.0,000000000000211111111021,0.0,NaN,0,500.0,0,0,1,0,1,0,0,0.0,0.0,0.0,741.0,277.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2022-03-31 00:00:00,1996-06-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,1,NaN
573779,51,50,5197230000230131,2019-07-31 00:00:00,999,-69199.96,-69199.96,0.00,5.343960e+03,NaN,0,0.0000,0.0,0,0.0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.00,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-31 00:00:00,2019-01-02 00:00:00,,,NaN,,,9,204000.0,0.0,00010000000010,0.0,NaN,0,185000.0,0,0,1,1,1,0,0,0.0,0.0,0.0,728.0,13.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,2022-06-30 00:00:00,2018-06-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30275.9264,1,NaN

In [9]:
account_history.RecordDate =  pd.to_datetime(account_history.RecordDate)
account_history.PastDueDate1 =  pd.to_datetime(account_history.PastDueDate1)
account_history.PastDueDate2 =  pd.to_datetime(account_history.PastDueDate2)
account_history.LastRcvdPmtDate =  pd.to_datetime(account_history.LastRcvdPmtDate)
account_history.BlockCode1Date =  pd.to_datetime(account_history.BlockCode1Date)
account_history.BlockCode2Date =  pd.to_datetime(account_history.BlockCode2Date)
account_history.MaturityDate =  pd.to_datetime(account_history.MaturityDate)
account_history.ExpirationDate =  pd.to_datetime(account_history.ExpirationDate)
account_history.OpenDate =  pd.to_datetime(account_history.OpenDate)
account_history.CancelDate =  pd.to_datetime(account_history.CancelDate)
account_history.ExpirationDate =  pd.to_datetime(account_history.ExpirationDate)

In [10]:
account_history.RecordDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.PastDueDate1.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.PastDueDate2.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.LastRcvdPmtDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.BlockCode1Date.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.BlockCode2Date.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.MaturityDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.ExpirationDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.OpenDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.CancelDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)
account_history.ExpirationDate.fillna(pd.to_datetime('1900-01-01'), inplace=True)

In [11]:
account_history.head()

,BankId,AppId,Acct,RecordDate,TypeId,TotalBalance,PrincipalBalance,InterestBalance,AverageBalance,Rate,DaysPastDue,InterestMTD,NumPmtsPastDue,Num30DPD,Amt30DPD,Num60DPD,Amt60DPD,Num90DPD,Amt90DPD,Num120DPD,Amt120DPD,Num150DPD,Amt150DPD,Num180DPD,Amt180DPD,Num210DPD,Amt210DPD,IntAccruedToDate,AmountPmtPastDue,TotalPrinPastDue,MinBalance,IntAccruedMTD,NumDaysOverdrawn,PrimeRateNum,LateFees,PastDueDate1,PastDueDate2,PastDueInt1,PastDueInt2,PastDuePrin1,PastDuePrin2,LastRcvdPmtDate,BlockCode1Date,BlockCodeId1,BlockReason1,BlockCode2Date,BlockCodeId2,BlockReason2,StatusId,CreditLimit,CashBalance,HDelinquency,CurrentAmtDue,ChargeOffStatusId,CurrencyId,LastPmtAmount,BucketReal,Gold,Opened,ActiveInvoluntary,Transactor,OpenedThisMonth,UpgradedThisMonth,NRFF,PFTR,Profitability,BehaviorScore,MOB,NRFF2,LoanStatus,LoanTermStatus,LoanCondition,PCTID,BranchId,OfficerId,MaturityDate,TermDays,ExpirationDate,OpenDate,CancelDate,CapitalCastigado,SaldoCastigado,MontoRecuperado,CurrBillPrin,CurrBillInt,CurrBillDueDate,MtdAvgBal,ChargeOffDate,CurrPmtType,PrinTranAddr,AmtTranDDR,NextSchedBill,ANR,RISK,Rate_Formateada
0,51,20,1000632011,2019-07-31,2,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,NaN,NaN,1900-01-01,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,512.0,NaN,?,?,?,NaN,2.0,EL,1900-01-01,0.0,1900-01-01,1959-02-04,1900-01-01,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
1,51,20,1000785012,2019-07-31,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,NaN,NaN,1900-01-01,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,121.0,NaN,?,?,?,NaN,2.0,EL,1900-01-01,0.0,1900-01-01,1991-09-30,1900-01-01,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
2,51,20,1001086029,2019-07-31,2,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,NaN,NaN,1900-01-01,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,627.0,NaN,?,?,?,NaN,3.0,AR,1900-01-01,0.0,1900-01-01,1952-01-15,1900-01-01,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
3,51,20,1001610011,2019-07-31,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,NaN,NaN,1900-01-01,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000011111...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,296.0,NaN,?,?,?,NaN,3.0,AR,1900-01-01,0.0,1900-01-01,1991-07-01,1900-01-01,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0
4,51,20,1001944017,2019-07-31,1,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,NaN,NaN,1900-01-01,NaN,NaN,4,0.0,NaN,0000000000000000000000000000000000000000000000...,NaN,NaN,0,NaN,0,0,0,0,1,0,0,0.0,0.0,0.0,NaN,121.0,NaN,?,?,?,NaN,2.0,EL,1900-01-01,0.0,1900-01-01,1991-09-30,1900-01-01,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,-1,0.0

In [12]:
account_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 639656 entries, 0 to 639655
Data columns (total 95 columns):
BankId               639656 non-null int64
AppId                639656 non-null int64
Acct                 639656 non-null int64
RecordDate           639656 non-null datetime64[ns]
TypeId               639656 non-null int64
TotalBalance         639656 non-null float64
PrincipalBalance     639656 non-null float64
InterestBalance      639656 non-null float64
AverageBalance       639656 non-null float64
Rate                 530881 non-null float64
DaysPastDue          639656 non-null int64
InterestMTD          467228 non-null float64
NumPmtsPastDue       639656 non-null float64
Num30DPD             639656 non-null int64
Amt30DPD             108775 non-null float64
Num60DPD             639656 non-null int64
Amt60DPD             108775 non-null float64
Num90DPD             639656 non-null int64
Amt90DPD             108775 non-null float64
Num120DPD            108775 non-null float64
Amt120DPD            108775 non-null float64
Num150DPD            108775 non-null float64
Amt150DPD            108775 non-null float64
Num180DPD            108775 non-null float64
Amt180DPD            108775 non-null float64
Num210DPD            108775 non-null float64
Amt210DPD            108775 non-null float64
IntAccruedToDate     530881 non-null float64
AmountPmtPastDue     639656 non-null float64
TotalPrinPastDue     530881 non-null float64
MinBalance           530881 non-null float64
IntAccruedMTD        539986 non-null float64
NumDaysOverdrawn     530881 non-null float64
PrimeRateNum         530881 non-null float64
LateFees             639656 non-null float64
PastDueDate1         639656 non-null datetime64[ns]
PastDueDate2         639656 non-null datetime64[ns]
PastDueInt1          530881 non-null float64
PastDueInt2          530881 non-null float64
PastDuePrin1         530881 non-null float64
PastDuePrin2         530881 non-null float64
LastRcvdPmtDate      639656 non-null datetime64[ns]
BlockCode1Date       639656 non-null datetime64[ns]
BlockCodeId1         108775 non-null object
BlockReason1         108775 non-null object
BlockCode2Date       639656 non-null datetime64[ns]
BlockCodeId2         108775 non-null object
BlockReason2         108775 non-null object
StatusId             639656 non-null int64
CreditLimit          639656 non-null float64
CashBalance          108775 non-null float64
HDelinquency         566898 non-null object
CurrentAmtDue        108775 non-null float64
ChargeOffStatusId    0 non-null float64
CurrencyId           639656 non-null int64
LastPmtAmount        108775 non-null float64
BucketReal           639656 non-null int64
Gold                 639656 non-null int64
Opened               639656 non-null int64
ActiveInvoluntary    639656 non-null int64
Transactor           639656 non-null int64
OpenedThisMonth      639656 non-null int64
UpgradedThisMonth    639656 non-null int64
NRFF                 639656 non-null float64
PFTR                 639656 non-null float64
Profitability        639656 non-null float64
BehaviorScore        108775 non-null float64
MOB                  639651 non-null float64
NRFF2                0 non-null float64
LoanStatus           530881 non-null object
LoanTermStatus       530881 non-null object
LoanCondition        530881 non-null object
PCTID                108775 non-null float64
BranchId             530881 non-null float64
OfficerId            530881 non-null object
MaturityDate         639656 non-null datetime64[ns]
TermDays             530881 non-null float64
ExpirationDate       639656 non-null datetime64[ns]
OpenDate             639656 non-null datetime64[ns]
CancelDate           639656 non-null datetime64[ns]
CapitalCastigado     530881 non-null float64
SaldoCastigado       530881 non-null float64
MontoRecuperado      530881 non-null float64
CurrBillPrin         530881 non-null float64
CurrBillInt          530881 non-null float64
CurrBillDueDate      2606 non-null object
MtdAvgBal            530881 non-null float64
ChargeOffDate        0 non-null float64
CurrPmtType          139014 non-null float64
PrinTranAddr         530881 non-null float64
AmtTranDDR           530881 non-null float64
NextSchedBill        185307 non-null object
ANR                  1217 non-null float64
RISK                 639656 non-null int64
Rate_Formateada      530881 non-null float64
dtypes: datetime64[ns](10), float64(56), int64(18), object(11)
memory usage: 463.6+ MB

In [13]:
# account_history.to_json('../vol/web/media/insumos/automatic/fixed/ACCOUNT_HISTORY.json', orient='records', date_format='iso')

In [14]:
# account_history_json = pd.read_json('../vol/web/media/insumos/automatic/ACCOUNT_HISTORY.json')

In [16]:
#account_history_json.head()

In [18]:
account_history.to_csv('../vol/web/media/insumos/automatic/fixed/ACCOUNT_HISTORY.txt', sep='~', date_format='%d/%m/%Y', index=False)