In [1]:
import pandas as pd

In [2]:
pd.options.display.max_columns = 500
pd.options.display.max_rows = 500

In [3]:
names = [
    'RIF', 
    'NombreRazonSocial', 
    'NumeroCredito', 
    'InteresesEfectivamenteCobrados', 
    'PorcentajeComisionFLAT', 
    'MontoComisionFLAT', 
    'PeriodicidadPagoEspecialCapital', 
    'FechaCambioEstatusCredito',
    'FechaExigibilidadPagolaultimaCuotaPagada', 
    'FechaRegistroVencidaLitigioCastigada', 
    'TipoIndustria', 
    'TipoBeneficiarioSectorManufacturero', 
    'TipoBeneficiarioSectorTurismo', 
    'BeneficiarioEspecial', 
    'FechaEmisionCertificacionBeneficiarioEspecial', 
    'TipoVivienda', 
    'FechaFinPeriodoGraciaPagoInteres', 
    'CapitalTransferido', 
    'FechaCambioEstatusCapitalTransferido', 
]

parse_dates = [
    'FechaExigibilidadPagolaultimaCuotaPagada',
    'FechaRegistroVencidaLitigioCastigada',
    'FechaEmisionCertificacionBeneficiarioEspecial',
    'FechaFinPeriodoGraciaPagoInteres',
    'FechaCambioEstatusCapitalTransferido',
    'FechaCambioEstatusCredito'
]

na_values = {
    'InteresesEfectivamenteCobrados': 0, 
    'PorcentajeComisionFLAT': 0,
    'MontoComisionFLAT': 0,
    'PeriodicidadPagoEspecialCapital': 0,
    'FechaExigibilidadPagolaultimaCuotaPagada': pd.to_datetime('1900-01-01'),
    'FechaRegistroVencidaLitigioCastigada': pd.to_datetime('1900-01-01'),
    'TipoIndustria': 0,
    'TipoBeneficiarioSectorManufacturero': 0,
    'TipoBeneficiarioSectorTurismo': 0,
    'BeneficiarioEspecial': 0,
    'FechaEmisionCertificacionBeneficiarioEspecial': pd.to_datetime('1900-01-01'),
    'TipoVivienda': 0,
    'FechaFinPeriodoGraciaPagoInteres': pd.to_datetime('1900-01-01'),
    'CapitalTransferido': 0,
    'FechaCambioEstatusCapitalTransferido': pd.to_datetime('1900-01-01'),
    'FechaCambioEstatusCredito': pd.to_datetime('1900-01-01'),
}

HCP = 7 # Hipotecario Corto Plazo
TURISMO = 8 # Turismo
MANUFACTURA = 10 # Manufactura
AGRICOLA_ICG = 11 # Agricola ICG

In [4]:
g_construccion = pd.read_excel('../vol/web/media/insumos/manual/AT04_Construccion_Noviembre_2019_.xls', 
                               usecols='C:U',   
                               header=1,)
g_agricola = pd.read_excel('../vol/web/media/insumos/manual/AT04_Gaveta agricola ICG Noviembre 2019.xls', 
                               usecols='B:T', 
                               header=1,
                               names=names,)
g_manufactura = pd.read_excel('../vol/web/media/insumos/manual/AT04_Manufactura Noviembre 2019.xls',
                              usecols='B:T',
                              names=names,)
g_turismo = pd.read_excel('../vol/web/media/insumos/manual/AT04_Turism_Noviembre_2019_.xls',
                          usecols='B:T',
                          names=names,
                          converters={7:str, 8:str})

# Gaveta Construccion

In [5]:
cols = list(g_construccion.columns.values)
order = [0, 1, 2, 3, 4, 5, 6, 18, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
cols = [cols[i] for i in order]

In [6]:
g_construccion = g_construccion[cols].copy()

In [7]:
g_construccion.columns = names

In [8]:
g_construccion[parse_dates] = g_construccion[parse_dates].apply(lambda x:pd.to_datetime(x, format='%Y%m%d', errors='coerce'))

In [9]:
g_construccion.fillna(value=na_values, inplace=True)

In [10]:
g_construccion['TypeCD'] = HCP

In [11]:
g_construccion

,RIF,NombreRazonSocial,NumeroCredito,InteresesEfectivamenteCobrados,PorcentajeComisionFLAT,MontoComisionFLAT,PeriodicidadPagoEspecialCapital,FechaCambioEstatusCredito,FechaExigibilidadPagolaultimaCuotaPagada,FechaRegistroVencidaLitigioCastigada,TipoIndustria,TipoBeneficiarioSectorManufacturero,TipoBeneficiarioSectorTurismo,BeneficiarioEspecial,FechaEmisionCertificacionBeneficiarioEspecial,TipoVivienda,FechaFinPeriodoGraciaPagoInteres,CapitalTransferido,FechaCambioEstatusCapitalTransferido,TypeCD
0,314873709,"TecnoServicios de Occidente, C.A.",8192320301,0,0,0,0,1900-01-01,1900-01-01,1900-01-01,0,0,0,0,1900-01-01,1,1900-01-01,0,1900-01-01,7
1,306579630,Constructora Dango C.A.,8191340308,0,0,0,0,1900-01-01,1900-01-01,1900-01-01,0,0,0,0,1900-01-01,1,1900-01-01,0,1900-01-01,7

In [12]:
g_construccion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 20 columns):
RIF                                              2 non-null int64
NombreRazonSocial                                2 non-null object
NumeroCredito                                    2 non-null int64
InteresesEfectivamenteCobrados                   2 non-null int64
PorcentajeComisionFLAT                           2 non-null int64
MontoComisionFLAT                                2 non-null int64
PeriodicidadPagoEspecialCapital                  2 non-null int64
FechaCambioEstatusCredito                        2 non-null datetime64[ns]
FechaExigibilidadPagolaultimaCuotaPagada         2 non-null datetime64[ns]
FechaRegistroVencidaLitigioCastigada             2 non-null datetime64[ns]
TipoIndustria                                    2 non-null int64
TipoBeneficiarioSectorManufacturero              2 non-null int64
TipoBeneficiarioSectorTurismo                    2 non-null int64
BeneficiarioEspecial                             2 non-null int64
FechaEmisionCertificacionBeneficiarioEspecial    2 non-null datetime64[ns]
TipoVivienda                                     2 non-null int64
FechaFinPeriodoGraciaPagoInteres                 2 non-null datetime64[ns]
CapitalTransferido                               2 non-null int64
FechaCambioEstatusCapitalTransferido             2 non-null datetime64[ns]
TypeCD                                           2 non-null int64
dtypes: datetime64[ns](6), int64(13), object(1)
memory usage: 448.0+ bytes

# Gaveta Agricola

In [13]:
g_agricola[parse_dates] = g_agricola[parse_dates].apply(lambda x:pd.to_datetime(x, format='%Y/%m/%d', errors='coerce'))

In [14]:
g_agricola.fillna(value=na_values, inplace=True)

In [15]:
g_agricola['TypeCD'] = AGRICOLA_ICG

In [16]:
g_agricola

,RIF,NombreRazonSocial,NumeroCredito,InteresesEfectivamenteCobrados,PorcentajeComisionFLAT,MontoComisionFLAT,PeriodicidadPagoEspecialCapital,FechaCambioEstatusCredito,FechaExigibilidadPagolaultimaCuotaPagada,FechaRegistroVencidaLitigioCastigada,TipoIndustria,TipoBeneficiarioSectorManufacturero,TipoBeneficiarioSectorTurismo,BeneficiarioEspecial,FechaEmisionCertificacionBeneficiarioEspecial,TipoVivienda,FechaFinPeriodoGraciaPagoInteres,CapitalTransferido,FechaCambioEstatusCapitalTransferido,TypeCD
0,306218734,Agropecuaria El Docoro C.A.,8190880303,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
1,300058085,Agropecuaria Nivar C.A.,8192200301,8098520.55,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-08,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
2,298046538,Agropecuaria Tierra de Agua C.A.,8183240301,11921.00,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-15,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
3,298046538,Agropecuaria Tierra de Agua C.A.,8190520301,13189.22,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-20,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
4,801487,Hidroponias Venezolanas C.A.,8183410301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
5,801487,Hidroponias Venezolanas C.A.,8191370302,4657171.25,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-18,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
6,801487,Hidroponias Venezolanas C.A.,8192040301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
7,801487,Hidroponias Venezolanas C.A.,8192760302,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
8,801487,Hidroponias Venezolanas C.A.,8192830301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
9,85034056,Inversiones San Luis C.A.,8190880304,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
10,2017805,Productos Alimenticios Kellys C.A.,8183310302,34883.33,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-27,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
11,2017805,Productos Alimenticios Kellys C.A.,8190510301,21660.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-20,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
12,2017805,Productos Alimenticios Kellys C.A.,8191440301,9200088.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-26,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
13,2017805,Productos Alimenticios Kellys C.A.,8191980301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
14,2017805,Productos Alimenticios Kellys C.A.,8192280302,6940013.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-15,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
15,2017805,Productos Alimenticios Kellys C.A.,8192760303,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
16,2017805,Productos Alimenticios Kellys C.A.,8192830304,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11

In [17]:
g_agricola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 20 columns):
RIF                                              17 non-null int64
NombreRazonSocial                                17 non-null object
NumeroCredito                                    17 non-null int64
InteresesEfectivamenteCobrados                   17 non-null float64
PorcentajeComisionFLAT                           17 non-null float64
MontoComisionFLAT                                17 non-null float64
PeriodicidadPagoEspecialCapital                  17 non-null float64
FechaCambioEstatusCredito                        17 non-null datetime64[ns]
FechaExigibilidadPagolaultimaCuotaPagada         17 non-null datetime64[ns]
FechaRegistroVencidaLitigioCastigada             17 non-null datetime64[ns]
TipoIndustria                                    17 non-null float64
TipoBeneficiarioSectorManufacturero              17 non-null float64
TipoBeneficiarioSectorTurismo                    17 non-null float64
BeneficiarioEspecial                             17 non-null float64
FechaEmisionCertificacionBeneficiarioEspecial    17 non-null datetime64[ns]
TipoVivienda                                     17 non-null float64
FechaFinPeriodoGraciaPagoInteres                 17 non-null datetime64[ns]
CapitalTransferido                               17 non-null float64
FechaCambioEstatusCapitalTransferido             17 non-null datetime64[ns]
TypeCD                                           17 non-null int64
dtypes: datetime64[ns](6), float64(10), int64(3), object(1)
memory usage: 2.8+ KB

# Gaveta Manufactura

In [18]:
g_manufactura[parse_dates] = g_manufactura[parse_dates].apply(lambda x:pd.to_datetime(x, format='%Y/%m/%d', errors='coerce'))

In [19]:
g_manufactura.fillna(value=na_values, inplace=True)

In [20]:
g_manufactura['TypeCD'] = MANUFACTURA

In [21]:
g_manufactura

,RIF,NombreRazonSocial,NumeroCredito,InteresesEfectivamenteCobrados,PorcentajeComisionFLAT,MontoComisionFLAT,PeriodicidadPagoEspecialCapital,FechaCambioEstatusCredito,FechaExigibilidadPagolaultimaCuotaPagada,FechaRegistroVencidaLitigioCastigada,TipoIndustria,TipoBeneficiarioSectorManufacturero,TipoBeneficiarioSectorTurismo,BeneficiarioEspecial,FechaEmisionCertificacionBeneficiarioEspecial,TipoVivienda,FechaFinPeriodoGraciaPagoInteres,CapitalTransferido,FechaCambioEstatusCapitalTransferido,TypeCD
0,299058157,KC Publicidad C.A.,8192820309,0.0,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,1,1,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,10
1,298227184,"Alimentos Procesados y Comercializados, C.A.",8192280303,13513500.0,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-15,1,1,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,10

In [22]:
g_manufactura.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 20 columns):
RIF                                              2 non-null int64
NombreRazonSocial                                2 non-null object
NumeroCredito                                    2 non-null int64
InteresesEfectivamenteCobrados                   2 non-null float64
PorcentajeComisionFLAT                           2 non-null float64
MontoComisionFLAT                                2 non-null float64
PeriodicidadPagoEspecialCapital                  2 non-null float64
FechaCambioEstatusCredito                        2 non-null datetime64[ns]
FechaExigibilidadPagolaultimaCuotaPagada         2 non-null datetime64[ns]
FechaRegistroVencidaLitigioCastigada             2 non-null datetime64[ns]
TipoIndustria                                    2 non-null int64
TipoBeneficiarioSectorManufacturero              2 non-null int64
TipoBeneficiarioSectorTurismo                    2 non-null float64
BeneficiarioEspecial                             2 non-null float64
FechaEmisionCertificacionBeneficiarioEspecial    2 non-null datetime64[ns]
TipoVivienda                                     2 non-null float64
FechaFinPeriodoGraciaPagoInteres                 2 non-null datetime64[ns]
CapitalTransferido                               2 non-null float64
FechaCambioEstatusCapitalTransferido             2 non-null datetime64[ns]
TypeCD                                           2 non-null int64
dtypes: datetime64[ns](6), float64(8), int64(5), object(1)
memory usage: 448.0+ bytes

# Gaveta Turismo

In [23]:
g_turismo[parse_dates] = g_turismo[parse_dates].apply(lambda x:pd.to_datetime(x, format='%Y%m%d', errors='coerce'))

In [24]:
g_turismo.fillna(value=na_values, inplace=True)

In [25]:
g_turismo['TypeCD'] = TURISMO

In [26]:
g_turismo

,RIF,NombreRazonSocial,NumeroCredito,InteresesEfectivamenteCobrados,PorcentajeComisionFLAT,MontoComisionFLAT,PeriodicidadPagoEspecialCapital,FechaCambioEstatusCredito,FechaExigibilidadPagolaultimaCuotaPagada,FechaRegistroVencidaLitigioCastigada,TipoIndustria,TipoBeneficiarioSectorManufacturero,TipoBeneficiarioSectorTurismo,BeneficiarioEspecial,FechaEmisionCertificacionBeneficiarioEspecial,TipoVivienda,FechaFinPeriodoGraciaPagoInteres,CapitalTransferido,FechaCambioEstatusCapitalTransferido,TypeCD
0,1428860,"ACO ALQUILER, S.A.",8191780303,1288888.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-26,0,0,1,0,1900-01-01,0,1900-01-01,0,1900-01-01,8
1,450730,"RENTA MOTOR, C.A.",8191290301,13.99,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-22,0,0,1,0,1900-01-01,0,1900-01-01,0,1900-01-01,8
2,303313019,INVERSORA ISLAMAR,8173270302,1219907.41,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-14,0,0,1,0,1900-01-01,0,1900-01-01,0,1900-01-01,8

In [27]:
g_turismo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 20 columns):
RIF                                              3 non-null int64
NombreRazonSocial                                3 non-null object
NumeroCredito                                    3 non-null int64
InteresesEfectivamenteCobrados                   3 non-null float64
PorcentajeComisionFLAT                           3 non-null float64
MontoComisionFLAT                                3 non-null float64
PeriodicidadPagoEspecialCapital                  3 non-null float64
FechaCambioEstatusCredito                        3 non-null datetime64[ns]
FechaExigibilidadPagolaultimaCuotaPagada         3 non-null datetime64[ns]
FechaRegistroVencidaLitigioCastigada             3 non-null datetime64[ns]
TipoIndustria                                    3 non-null int64
TipoBeneficiarioSectorManufacturero              3 non-null int64
TipoBeneficiarioSectorTurismo                    3 non-null int64
BeneficiarioEspecial                             3 non-null int64
FechaEmisionCertificacionBeneficiarioEspecial    3 non-null datetime64[ns]
TipoVivienda                                     3 non-null int64
FechaFinPeriodoGraciaPagoInteres                 3 non-null datetime64[ns]
CapitalTransferido                               3 non-null int64
FechaCambioEstatusCapitalTransferido             3 non-null datetime64[ns]
TypeCD                                           3 non-null int64
dtypes: datetime64[ns](6), float64(4), int64(9), object(1)
memory usage: 608.0+ bytes

# Concatenating Them All

In [28]:
gavetas = pd.concat([g_agricola, g_construccion, g_manufactura, g_turismo], ignore_index=True)

In [29]:
gavetas

,RIF,NombreRazonSocial,NumeroCredito,InteresesEfectivamenteCobrados,PorcentajeComisionFLAT,MontoComisionFLAT,PeriodicidadPagoEspecialCapital,FechaCambioEstatusCredito,FechaExigibilidadPagolaultimaCuotaPagada,FechaRegistroVencidaLitigioCastigada,TipoIndustria,TipoBeneficiarioSectorManufacturero,TipoBeneficiarioSectorTurismo,BeneficiarioEspecial,FechaEmisionCertificacionBeneficiarioEspecial,TipoVivienda,FechaFinPeriodoGraciaPagoInteres,CapitalTransferido,FechaCambioEstatusCapitalTransferido,TypeCD
0,306218734,Agropecuaria El Docoro C.A.,8190880303,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
1,300058085,Agropecuaria Nivar C.A.,8192200301,8098520.55,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-08,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
2,298046538,Agropecuaria Tierra de Agua C.A.,8183240301,11921.00,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-15,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
3,298046538,Agropecuaria Tierra de Agua C.A.,8190520301,13189.22,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-20,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
4,801487,Hidroponias Venezolanas C.A.,8183410301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
5,801487,Hidroponias Venezolanas C.A.,8191370302,4657171.25,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-18,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
6,801487,Hidroponias Venezolanas C.A.,8192040301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
7,801487,Hidroponias Venezolanas C.A.,8192760302,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
8,801487,Hidroponias Venezolanas C.A.,8192830301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
9,85034056,Inversiones San Luis C.A.,8190880304,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
10,2017805,Productos Alimenticios Kellys C.A.,8183310302,34883.33,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-27,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
11,2017805,Productos Alimenticios Kellys C.A.,8190510301,21660.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-20,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
12,2017805,Productos Alimenticios Kellys C.A.,8191440301,9200088.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-26,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
13,2017805,Productos Alimenticios Kellys C.A.,8191980301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
14,2017805,Productos Alimenticios Kellys C.A.,8192280302,6940013.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-15,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
15,2017805,Productos Alimenticios Kellys C.A.,8192760303,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
16,2017805,Productos Alimenticios Kellys C.A.,8192830304,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,11
17,314873709,"TecnoServicios de Occidente, C.A.",8192320301,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1.0,1900-01-01,0.0,1900-01-01,7
18,306579630,Constructora Dango C.A.,8191340308,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,0.0,0.0,0.0,0.0,1900-01-01,1.0,1900-01-01,0.0,1900-01-01,7
19,299058157,KC Publicidad C.A.,8192820309,0.00,0.0,0.0,0.0,1900-01-01,1900-01-01,1900-01-01,1.0,1.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,10
20,298227184,"Alimentos Procesados y Comercializados, C.A.",8192280303,13513500.00,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-15,1.0,1.0,0.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,10
21,1428860,"ACO ALQUILER, S.A.",8191780303,1288888.89,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-26,0.0,0.0,1.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,8
22,450730,"RENTA MOTOR, C.A.",8191290301,13.99,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-22,0.0,0.0,1.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,8
23,303313019,INVERSORA ISLAMAR,8173270302,1219907.41,0.0,0.0,0.0,1900-01-01,1900-01-01,2019-11-14,0.0,0.0,1.0,0.0,1900-01-01,0.0,1900-01-01,0.0,1900-01-01,8

In [30]:
gavetas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 20 columns):
RIF                                              24 non-null int64
NombreRazonSocial                                24 non-null object
NumeroCredito                                    24 non-null int64
InteresesEfectivamenteCobrados                   24 non-null float64
PorcentajeComisionFLAT                           24 non-null float64
MontoComisionFLAT                                24 non-null float64
PeriodicidadPagoEspecialCapital                  24 non-null float64
FechaCambioEstatusCredito                        24 non-null datetime64[ns]
FechaExigibilidadPagolaultimaCuotaPagada         24 non-null datetime64[ns]
FechaRegistroVencidaLitigioCastigada             24 non-null datetime64[ns]
TipoIndustria                                    24 non-null float64
TipoBeneficiarioSectorManufacturero              24 non-null float64
TipoBeneficiarioSectorTurismo                    24 non-null float64
BeneficiarioEspecial                             24 non-null float64
FechaEmisionCertificacionBeneficiarioEspecial    24 non-null datetime64[ns]
TipoVivienda                                     24 non-null float64
FechaFinPeriodoGraciaPagoInteres                 24 non-null datetime64[ns]
CapitalTransferido                               24 non-null float64
FechaCambioEstatusCapitalTransferido             24 non-null datetime64[ns]
TypeCD                                           24 non-null int64
dtypes: datetime64[ns](6), float64(10), int64(3), object(1)
memory usage: 3.9+ KB

In [31]:
gavetas.to_csv('../vol/web/media/insumos/manual/fixed/GavetasICG.txt', sep='~', date_format='%d/%m/%Y', index=False)