In [1]:
import pandas as pd

In [2]:
pd.options.display.max_columns = 500
pd.options.display.max_rows = 10000

In [3]:
labels = [
    'P8NOTE', 
    'P8TINC', 
    'P8FVUC', 
    'P8FCCC', 
    'P8FVUI', 
    'P8FCCI', 
    'P8NRCV', 
    'P8MV30', 
    'P8MV60', 
    'P8MV90', 
    'P8MV12', 
    'P8MV18', 
    'P8MV1A', 
    'P8MVM1', 
    'P8RPCV', 
    'P8LINT', 
    'P8FCTC', 
    'P8MOCA', 
    'P8MOIN', 
    'P8TRXN', 
    'P8PRAN',
    ]

fwidths = [11, 13, 8, 8, 8, 8, 8, 13, 13, 13, 13, 13, 13, 13, 13, 13, 8, 13, 13, 2, 11,]

In [4]:
lnp860 = pd.read_fwf('../vol/web/media/insumos/automatic/lnp860', widths = fwidths, names = labels)

In [5]:
lnp860.head()

,P8NOTE,P8TINC,P8FVUC,P8FCCC,P8FVUI,P8FCCI,P8NRCV,P8MV30,P8MV60,P8MV90,P8MV12,P8MV18,P8MV1A,P8MVM1,P8RPCV,P8LINT,P8FCTC,P8MOCA,P8MOIN,P8TRXN,P8PRAN
0,600003626,4659987,30012019,7022019,30012019,7022019,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0
1,1931652739,30000000,15062003,16092003,15042003,3072003,00000003,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0
2,6000000069,9870000,28092007,28092007,28092007,7112007,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,68.0,0
3,6000000269,6924976,30072018,30072018,28022019,28022019,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0
4,6000000531,6953262,29072018,30072018,29122018,2012019,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0

In [6]:
lnp860.tail()

,P8NOTE,P8TINC,P8FVUC,P8FCCC,P8FVUI,P8FCCI,P8NRCV,P8MV30,P8MV60,P8MV90,P8MV12,P8MV18,P8MV1A,P8MVM1,P8RPCV,P8LINT,P8FCTC,P8MOCA,P8MOIN,P8TRXN,P8PRAN
4293,13113175525,65000000,1031999,27051999,1021999,10021999,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0
4294,20511062213,58000000,20062000,20062000,20062000,20062000,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0
4295,22514173501,25000000,15042006,7072006,15022006,31032006,00000004,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0
4296,27110061374,52000000,2022001,9042001,2032001,25092002,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,68.0,0
4297,73110058921,49000000,7032001,6042001,7032001,5042001,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0

In [7]:
lnp860.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4298 entries, 0 to 4297
Data columns (total 21 columns):
P8NOTE    4298 non-null int64
P8TINC    4298 non-null int64
P8FVUC    4298 non-null int64
P8FCCC    4298 non-null int64
P8FVUI    4298 non-null int64
P8FCCI    4298 non-null int64
P8NRCV    4298 non-null object
P8MV30    4298 non-null int64
P8MV60    4298 non-null int64
P8MV90    4298 non-null int64
P8MV12    4298 non-null int64
P8MV18    4298 non-null int64
P8MV1A    4298 non-null int64
P8MVM1    4298 non-null int64
P8RPCV    4298 non-null int64
P8LINT    4298 non-null int64
P8FCTC    4298 non-null int64
P8MOCA    4298 non-null int64
P8MOIN    4298 non-null object
P8TRXN    208 non-null float64
P8PRAN    4298 non-null int64
dtypes: float64(1), int64(18), object(2)
memory usage: 705.3+ KB

In [8]:
lnp860.P8PRAN.value_counts()

0             4279
6900000475       1
6900000116       1
6900000236       1
6900000280       1
6900000448       1
6900000460       1
6900000464       1
6900000476       1
6900000025       1
6900000511       1
6900000465       1
6900000477       1
6900000234       1
6900000270       1
6900000278       1
6900000223       1
6900000239       1
6900000459       1
6900000229       1
Name: P8PRAN, dtype: int64

In [9]:
lnp860.P8RPCV.value_counts()

0       3916
1        126
2         66
3         47
4         36
6         20
5         16
7          9
8          8
9          6
15         4
13         3
10         3
12         3
11         3
19         3
62         2
17         2
14         2
21         1
27         1
176        1
63         1
1808       1
69         1
64         1
33         1
321        1
73         1
93         1
129        1
305        1
23         1
375        1
22         1
30         1
38         1
150        1
194        1
738        1
1042       1
379        1
Name: P8RPCV, dtype: int64

In [10]:
lnp860.P8TINC.value_counts()

46000000         597
24000000         577
15000000         426
21000000         402
44000000         293
49000000         169
47000000         156
25000000         110
17000000          92
49750000          88
23000000          84
28000000          76
26000000          75
22000000          74
42000000          61
34000000          59
65000000          52
39000000          49
62000000          35
48000000          35
13000000          34
61000000          33
53000000          28
38000000          22
58000000          21
40000000          20
55000000          19
4660000           18
56000000          16
43500000          16
12638888          16
41000000          13
72000000          13
18000000          11
59000000          11
6660000           11
60000000          10
42500000           7
13288888           7
68000000           7
66000000           6
52000000           6
20000000           6
0                  6
48450000           5
13072222           5
43000000           5
27000000           5
63000000           5
4659999            5
19500000           5
19000000           5
6954999            5
6989999            4
5000000            4
14733333           4
6583834            4
13144444           3
13072125           3
7027999            3
1400000            3
7025000            3
6953262            3
44500000           3
6910000            3
7015591            2
4657976            2
37000000           2
4499172            2
8566165            2
6652694            2
8550000            2
4651024            2
6629653            2
10659999           2
4655759            2
6756999            2
4654892            2
9869999            2
4643675            2
9387103            2
10659998           2
4661249            2
12422222           2
64000000           2
8565097            2
4690113            1
10522621           1
4680386            1
6600550            1
9870000            1
6619071            1
8521696            1
4780713            1
4670107            1
4628307            1
4341777            1
6998048            1
6909999            1
9156666            1
8530004            1
9309942            1
9210000            1
6588244            1
6592326            1
4498856            1
4516570            1
4316603            1
4566461            1
4630032            1
4760307            1
4663043            1
4689473            1
8568387            1
6588000            1
6624902            1
3000000            1
4699874            1
6628075            1
2400000            1
6653704            1
4646696            1
10659996           1
4655268            1
10651852           1
4676202            1
6924976            1
7002810            1
7007474            1
4696800            1
4676326            1
6628077            1
7029509            1
4696864            1
4713256            1
4660010            1
4668000            1
4627278            1
4660058            1
4705958            1
4512666            1
9351799            1
12349999           1
4706511            1
4506153            1
6408436            1
4636941            1
6942999            1
4614810            1
2999999            1
8569161            1
4637017            1
8569193            1
4633011            1
8562347            1
4653703            1
4633063            1
6629864            1
4815366            1
6593038            1
4681542            1
9170301            1
4621249            1
4636500            1
4606325            1
6992250            1
4661636            1
6940615            1
4683673            1
4642697            1
6627844            1
4654211            1
4619233            1
10150560           1
4555428            1
7027636            1
7015101            1
6615758            1
6882000            1
4727520            1
10479981           1
8540470            1
4690222            1
4596000            1
10100744           1
4667423            1
4616234            1
6989877            1
6942810            1
4685924            1
4636800            1
4649090            1
10660001           1
6638850            1
6917250            1
13852908           1
4645116            1
4658185            1
4677912            1
4647669            1
4581199            1
4547332            1
4684799            1
10110000           1
6609999            1
10110032           1
4660012            1
6941793            1
4680865            1
4798285            1
6800592            1
8566034            1
8563902            1
6616374            1
8521016            1
7511359            1
4654400            1
4648257            1
4660028            1
4649962            1
4659987            1
45000000           1
4653999            1
8532774            1
4660011            1
4735800            1
6619999            1
4664157            1
7773047            1
30000000           1
7005060            1
5448600            1
6937499            1
4654000            1
4637632            1
10126296           1
4664285            1
9337790            1
4631110            1
8564869            1
13145585           1
4643132            1
46200000           1
6612206            1
4699384            1
8701335            1
4713743            1
6630711            1
4632833            1
6583636            1
4349332            1
4685193            1
4697491            1
4713899            1
4631999            1
8656320            1
5350530            1
6610017            1
13217154           1
4666456            1
4630846            1
4999999            1
4657469            1
4645714            1
4662130            1
4655999            1
7052181            1
13216667           1
6606322            1
4639687            1
7168990            1
6585313            1
4602857            1
4637714            1
8660002            1
4642284            1
9336328            1
4660013            1
4634444            1
4659096            1
4676888            1
9160000            1
7018736            1
39500000           1
6995999            1
6909985            1
4624421            1
4720702            1
10659091           1
4696130            1
4712526            1
4632657            1
4628571            1
4647042            1
4788107            1
6917478            1
7005750            1
9309999            1
4711998            1
7003713            1
4626000            1
4656386            1
6579818            1
4780285            1
4652697            1
9344680            1
6620846            1
4684769            1
4648675            1
4611829            1
8546058            1
4618000            1
4194073            1
4660021            1
9190177            1
4628068            1
4664680            1
13288885           1
4644278            1
6583735            1
4616705            1
4677098            1
41750000           1
4679177            1
7030325            1
4664888            1
13092415           1
4693578            1
6944347            1
4685454            1
4665048            1
4673280            1
6583361            1
6997333            1
4650823            1
4668750            1
4508684            1
4656148            1
4693058            1
8535114            1
9270857            1
6974608            1
4586666            1
4697280            1
9055440            1
7064800            1
4634181            1
4656408            1
9383212            1
4494639            1
4662585            1
4750908            1
4640608            1
9288000            1
4682052            1
4712799            1
8554898            1
9334302            1
4688307            1
9288141            1
7789021            1
4639199            1
7021066            1
8648217            1
10474060           1
9999999000000      1
8566277            1
4659937            1
6624000            1
4659989            1
4616532            1
4723000            1
4654989            1
4673796            1
4722620            1
7061478            1
4523999            1
4710438            1
4815360            1
4661302            1
4640848            1
8554603            1
7000200            1
7051732            1
10660007           1
4471200            1
6596791            1
7014611            1
7016680            1
4652394            1
Name: P8TINC, dtype: int64

In [11]:
lnp860.P8NRCV.value_counts()

00000000    2666
00000004     856
00000001     234
00000002     209
00000005     145
00000003     105
00000007      58
00000006      23
00000028       1
0002410L       1
Name: P8NRCV, dtype: int64

In [12]:
lnp860.P8MV30.value_counts()

0       3889
2         65
3         43
4         42
5         38
1         38
9         28
10        27
7         20
8         18
6         15
12        11
11         6
13         6
60         3
62         2
5464       2
130        2
27         2
63         2
26         2
1880       1
17         1
29         1
80         1
3589       1
480        1
272        1
128        1
85         1
76         1
68         1
36         1
20         1
57         1
1603       1
133        1
265        1
159        1
135        1
35         1
31         1
23         1
418        1
386        1
298        1
94         1
74         1
58         1
50         1
30         1
18         1
14         1
219        1
349        1
2344       1
289        1
1565       1
Name: P8MV30, dtype: int64

In [13]:
lnp860.tail(1)

,P8NOTE,P8TINC,P8FVUC,P8FCCC,P8FVUI,P8FCCI,P8NRCV,P8MV30,P8MV60,P8MV90,P8MV12,P8MV18,P8MV1A,P8MVM1,P8RPCV,P8LINT,P8FCTC,P8MOCA,P8MOIN,P8TRXN,P8PRAN
4297,73110058921,49000000,7032001,6042001,7032001,5042001,00000000,0,0,0,0,0,0,0,0,0,1011900,0,0000000000000,NaN,0

In [14]:
names = ['P8FVUC', 'P8FCCC', 'P8FVUI', 'P8FCCI', 'P8FCTC']
lnp860.P8FVUC =  pd.to_datetime(lnp860.P8FVUC, format='%d%m%Y', errors='coerce')
lnp860.P8FCCC =  pd.to_datetime(lnp860.P8FCCC, format='%d%m%Y', errors='coerce')
lnp860.P8FVUI =  pd.to_datetime(lnp860.P8FVUI, format='%d%m%Y', errors='coerce')
lnp860.P8FCCI =  pd.to_datetime(lnp860.P8FCCI, format='%d%m%Y', errors='coerce')
lnp860.P8FCTC =  pd.to_datetime(lnp860.P8FCTC, format='%d%m%Y', errors='coerce')
lnp860[names] = lnp860[names].fillna(pd.to_datetime('1900-01-01'))

In [15]:
lnp860.P8FVUC.value_counts()

1900-01-01    1397
2018-01-12      64
2017-12-12      55
2018-07-30      52
2019-07-20      47
2018-07-28      42
2017-06-12      41
2016-10-12      40
2016-09-18      37
2019-07-10      33
2017-08-12      33
2019-07-30      32
2018-07-29      31
2016-09-12      30
2016-11-12      29
2017-09-12      28
2017-03-12      28
2016-12-12      27
2017-11-12      27
2017-10-12      26
2018-01-18      25
2018-05-12      24
2017-04-12      24
2016-10-18      24
2017-02-12      24
2016-08-12      24
2017-05-12      22
2017-01-12      22
2018-07-26      22
2017-12-18      21
2017-07-12      21
2019-07-07      21
2019-07-04      21
2016-12-18      21
2019-05-10      20
2016-08-18      20
2019-07-06      19
2019-07-17      18
2016-05-12      18
2016-11-18      17
2019-07-23      17
2019-05-20      16
2017-05-18      16
2019-07-08      16
2018-07-22      16
2019-06-20      15
2019-07-13      15
2017-04-18      15
2017-06-18      15
2019-07-11      15
2018-07-18      15
2019-05-30      15
2018-07-27      15
2017-01-18      14
2017-09-18      14
2015-10-18      14
2017-03-18      13
2019-07-22      13
2016-03-18      13
2019-07-05      12
2016-06-12      12
2019-07-15      12
2019-07-16      12
2019-06-10      12
2018-04-12      12
2016-07-12      12
2017-02-18      12
2019-07-14      12
2015-12-12      12
2019-07-24      11
2014-12-12      11
2019-07-19      11
2018-05-18      11
2018-07-23      11
2019-06-30      11
2016-03-12      11
2017-08-18      11
2016-05-18      11
2015-07-12      11
2016-04-18      10
2015-08-12      10
2016-02-12      10
2016-02-18      10
2018-07-24      10
2017-07-18      10
2019-07-18       9
2019-06-25       9
2018-03-12       9
2019-06-26       9
2018-07-25       9
2018-02-12       9
2016-04-12       9
2015-02-12       9
2019-07-25       9
2018-07-31       9
2019-05-08       9
2015-11-12       8
2019-06-06       8
2018-06-18       8
2019-07-28       8
2019-06-28       8
2019-05-13       8
2019-07-21       8
2015-05-12       8
2017-11-18       8
2018-06-12       8
2019-06-07       8
2019-06-21       8
2017-10-18       8
2016-06-18       8
2019-06-14       7
2015-06-18       7
2009-03-18       7
2015-11-18       7
2015-10-12       7
2019-04-26       6
2019-05-09       6
2019-07-09       6
2018-07-20       6
2014-01-12       6
2019-02-04       6
2019-07-12       6
2018-08-16       6
2015-03-12       6
2019-04-16       6
2019-05-26       6
2015-09-12       6
2019-04-20       6
2019-06-11       6
2015-12-18       6
2019-01-30       6
2019-05-04       6
2009-01-18       6
2019-06-17       5
2019-05-16       5
2015-01-12       5
2019-06-15       5
2016-01-12       5
2019-05-17       5
2019-05-23       5
2018-02-18       5
2015-05-18       5
2014-03-12       5
2018-08-12       5
2019-07-26       5
2019-06-12       5
2012-05-18       5
2019-04-28       5
2008-06-18       5
2019-01-11       5
2019-06-04       5
2013-03-18       5
2019-02-10       5
2019-05-25       5
2019-06-09       5
2014-05-12       5
2014-10-12       5
2019-04-25       5
2019-05-05       5
2015-06-12       5
2018-09-30       4
2015-09-18       4
2019-06-13       4
2019-07-27       4
2019-06-29       4
2015-04-12       4
2018-07-19       4
2015-07-18       4
2019-05-14       4
2019-05-18       4
2014-01-18       4
2019-05-06       4
2018-08-23       4
2019-05-12       4
2008-11-18       4
2019-05-27       4
2015-08-18       4
2014-09-18       4
2019-04-21       4
2014-07-12       4
2013-09-12       4
2019-05-07       4
2016-07-18       4
2018-09-12       4
2019-06-23       4
2019-02-25       4
2013-12-12       4
2019-06-19       4
2019-05-11       4
2013-10-12       4
2019-01-26       3
2014-02-18       3
2019-03-22       3
2019-02-13       3
2018-08-26       3
2009-02-18       3
2018-08-05       3
2019-06-18       3
2010-01-18       3
2018-03-17       3
2018-09-10       3
2015-03-18       3
2013-08-18       3
2019-05-24       3
2018-08-18       3
2017-01-21       3
2009-08-21       3
2009-05-18       3
2012-09-18       3
2019-04-30       3
2015-06-21       3
2010-04-18       3
2015-04-18       3
2019-05-22       3
2014-11-18       3
2019-05-21       3
2009-11-18       3
2014-10-18       3
2019-04-17       3
2019-04-23       3
2018-08-27       3
2008-12-21       3
2019-01-18       3
2014-09-12       3
2016-01-18       3
2019-06-22       3
2011-01-18       3
2019-02-24       3
2014-04-12       3
2015-02-18       3
2012-03-18       3
2018-08-30       3
2011-10-18       3
2018-07-12       3
2013-07-12       3
2013-01-18       3
2013-02-12       3
2009-12-18       3
2019-05-19       3
2019-06-27       3
2016-08-21       3
2014-12-18       3
2014-04-18       3
2012-10-18       3
2013-01-12       3
2014-11-12       3
2018-08-25       3
2019-02-05       3
2012-01-12       2
2019-06-08       2
2019-01-28       2
2011-09-12       2
2008-11-21       2
2008-10-18       2
2019-02-11       2
2019-01-27       2
2013-06-12       2
2018-03-18       2
2012-12-18       2
2012-08-18       2
2013-08-12       2
2018-02-25       2
2008-03-18       2
2013-05-18       2
2011-07-18       2
2009-08-18       2
2018-02-10       2
2018-08-29       2
2010-06-21       2
2014-06-12       2
2011-12-12       2
2010-02-18       2
2008-09-18       2
2017-08-21       2
2019-01-21       2
2014-07-18       2
2012-05-12       2
2019-06-24       2
2019-02-20       2
2009-05-21       2
2018-07-21       2
2019-02-09       2
2010-07-12       2
2019-01-08       2
2018-12-14       2
2019-03-04       2
2018-06-06       2
2013-10-18       2
2019-05-15       2
2018-12-26       2
2011-05-18       2
2019-03-15       2
2008-02-18       2
2011-03-18       2
2018-08-22       2
2011-07-12       2
2019-04-15       2
2013-05-12       2
2016-07-21       2
2019-01-09       2
2009-11-21       2
2018-08-17       2
2019-06-16       2
2008-08-18       2
2014-06-18       2
2018-02-21       2
2009-06-18       2
2016-09-21       2
2019-03-23       2
2019-04-18       2
2018-01-30       2
2010-11-18       2
2019-06-05       2
2012-12-12       2
2018-08-28       2
2013-07-18       2
2017-10-21       2
2019-01-20       2
2019-01-10       2
2018-06-19       2
2013-04-12       2
2018-07-16       2
2019-02-06       2
2019-04-11       2
2014-08-21       2
2019-03-10       2
2019-02-28       2
2018-10-23       2
2019-05-28       2
2011-08-18       2
2018-04-18       2
2014-02-21       1
2010-11-12       1
2012-06-18       1
2019-04-19       1
2018-08-09       1
2019-02-21       1
2018-10-18       1
2019-03-12       1
2012-06-12       1
2010-08-12       1
2017-05-08       1
2017-12-15       1
2015-11-21       1
2019-07-29       1
2018-10-09       1
2018-03-20       1
2018-11-09       1
2018-03-04       1
2015-07-21       1
2010-07-21       1
2001-03-07       1
2019-01-14       1
2018-10-05       1
2009-02-21       1
2018-09-13       1
2006-10-28       1
2017-11-14       1
2009-01-26       1
2012-05-21       1
2017-12-23       1
2013-03-12       1
2009-07-21       1
2018-03-16       1
2018-03-05       1
2014-08-12       1
2018-05-30       1
2019-03-07       1
2009-08-12       1
2018-08-21       1
2013-12-18       1
2016-05-09       1
2018-02-05       1
2019-02-17       1
2013-02-18       1
2015-10-21       1
2010-12-12       1
2017-12-30       1
2018-11-17       1
2016-07-14       1
2019-01-13       1
2010-02-12       1
2019-02-26       1
2018-12-09       1
2019-04-14       1
2009-09-21       1
2018-04-07       1
2001-02-20       1
2018-05-08       1
2008-08-21       1
2019-01-22       1
2016-09-27       1
2014-03-29       1
2018-10-22       1
2018-09-04       1
2019-02-08       1
2009-12-21       1
2018-05-17       1
2019-04-29       1
2018-03-08       1
2011-10-29       1
2018-01-10       1
2012-11-18       1
2009-04-06       1
2000-06-20       1
2018-07-09       1
2017-02-28       1
2008-07-21       1
2019-01-17       1
2018-08-13       1
2017-09-09       1
2018-04-30       1
2017-10-22       1
2010-10-12       1
2018-12-27       1
2015-04-23       1
2018-09-25       1
2011-06-14       1
2018-09-17       1
2008-06-08       1
2019-01-04       1
2013-03-21       1
2015-02-25       1
2018-11-13       1
2008-07-30       1
2012-08-31       1
2018-04-29       1
2012-02-18       1
2017-09-27       1
2010-03-18       1
2018-09-11       1
2019-04-13       1
2008-10-15       1
2019-01-24       1
2009-09-18       1
2018-11-29       1
2018-03-15       1
2018-08-20       1
2014-08-18       1
2011-02-18       1
2019-02-15       1
2018-09-08       1
2018-12-20       1
2010-07-18       1
2011-06-21       1
2018-04-27       1
2018-05-10       1
2011-09-21       1
2018-10-15       1
2013-04-18       1
1999-05-10       1
2018-10-06       1
2016-12-21       1
2018-02-11       1
2019-01-15       1
2018-08-08       1
2012-08-12       1
2017-10-30       1
2019-01-25       1
2014-05-18       1
2018-12-11       1
2015-04-21       1
2003-06-15       1
2009-02-28       1
2009-06-21       1
2011-12-18       1
2012-11-12       1
1999-03-10       1
2018-11-24       1
2012-07-12       1
2017-04-24       1
2010-06-18       1
2016-09-25       1
2019-02-07       1
2015-02-28       1
2010-02-28       1
2019-01-29       1
2019-01-16       1
2018-08-24       1
2009-04-18       1
2017-01-26       1
2008-11-11       1
2018-10-07       1
2010-09-18       1
2016-05-25       1
2017-12-21       1
2019-04-22       1
2016-08-30       1
2016-10-21       1
2018-11-15       1
2017-01-30       1
2010-05-12       1
2017-02-26       1
2018-12-07       1
2018-04-14       1
2011-03-21       1
2018-01-25       1
2017-11-07       1
2018-09-24       1
2011-04-12       1
2014-06-21       1
2018-08-15       1
2018-03-10       1
2018-01-20       1
2011-03-16       1
2013-11-18       1
2016-01-13       1
2016-05-28       1
2016-11-21       1
2016-03-10       1
2014-02-12       1
2008-09-09       1
2017-08-10       1
2014-04-21       1
2009-12-25       1
2018-04-09       1
2018-02-06       1
2019-03-30       1
2011-01-13       1
2018-01-11       1
2009-03-30       1
2009-01-21       1
2014-01-21       1
2010-09-12       1
2019-02-14       1
2017-07-17       1
2018-06-20       1
2016-07-09       1
2007-09-28       1
2016-09-26       1
2018-12-10       1
2018-09-22       1
2017-03-21       1
2010-01-31       1
2019-03-28       1
2009-03-21       1
2018-09-29       1
2008-09-07       1
2010-03-12       1
2019-04-12       1
2008-07-27       1
2015-03-16       1
2018-11-14       1
2011-10-21       1
2011-12-28       1
2011-08-12       1
2018-12-15       1
2016-05-21       1
2018-06-11       1
2019-01-06       1
2006-04-15       1
2007-01-10       1
2018-10-19       1
2017-01-22       1
2018-06-05       1
2012-11-21       1
2011-05-12       1
2007-09-20       1
2019-01-12       1
2012-12-29       1
2010-04-12       1
2017-10-23       1
2018-06-13       1
2019-07-31       1
2018-09-05       1
2017-01-29       1
2012-04-18       1
2019-02-23       1
2011-11-12       1
2018-09-18       1
2013-09-18       1
2019-03-17       1
2018-12-28       1
2017-08-19       1
2012-08-21       1
2018-10-12       1
2019-04-08       1
2019-03-29       1
2017-11-08       1
2009-07-18       1
2018-08-10       1
Name: P8FVUC, dtype: int64

In [16]:
lnp860.head(1)

,P8NOTE,P8TINC,P8FVUC,P8FCCC,P8FVUI,P8FCCI,P8NRCV,P8MV30,P8MV60,P8MV90,P8MV12,P8MV18,P8MV1A,P8MVM1,P8RPCV,P8LINT,P8FCTC,P8MOCA,P8MOIN,P8TRXN,P8PRAN
0,600003626,4659987,2019-01-30,2019-02-07,2019-01-30,2019-02-07,00000000,0,0,0,0,0,0,0,0,0,1900-01-10,0,0000000000000,NaN,0

In [17]:
lnp860.P8NRCV = pd.to_numeric(lnp860.P8NRCV, errors='coerce')
lnp860.P8NRCV.fillna(0, inplace=True)
lnp860.P8NRCV = lnp860.P8NRCV.astype("int64")
lnp860.P8MOIN = pd.to_numeric(lnp860.P8NRCV, errors='coerce')
lnp860.P8MOIN.fillna(0, inplace=True)
lnp860.P8MOIN = lnp860.P8MOIN.astype("int64")

In [18]:
fields = ['P8MV30', 'P8MV60', 'P8MV90', 'P8MV12', 'P8MV18', 'P8MV1A', 'P8MVM1', 'P8RPCV', 'P8LINT', 'P8MOCA', 'P8MOIN']
lnp860[fields] = lnp860[fields].apply(lambda x:x/100)
lnp860.P8TINC = lnp860.P8TINC.apply(lambda x:x/1000000)

In [19]:
lnp860.loc[lnp860.P8NOTE == 7036589706]

,P8NOTE,P8TINC,P8FVUC,P8FCCC,P8FVUI,P8FCCI,P8NRCV,P8MV30,P8MV60,P8MV90,P8MV12,P8MV18,P8MV1A,P8MVM1,P8RPCV,P8LINT,P8FCTC,P8MOCA,P8MOIN,P8TRXN,P8PRAN
1644,7036589706,56.0,1900-01-01,1900-01-01,1900-01-01,1900-01-01,7,0.0,0.0,0.0,0.0,0.0,99999999.0,99999999.0,0.0,0.0,1900-01-10,0.0,0.07,NaN,0

In [20]:
lnp860.to_csv('../vol/web/media/insumos/automatic/fixed/lnp860.txt', sep='~', date_format='%d/%m/%Y', index=False)

In [21]:
# lnp860.to_json('../vol/web/media/insumos/automatic/fixed/lnp860.json', orient='records', date_format='%d/%m/%Y')