In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = 500
pd.options.display.max_rows = 10000

In [3]:
converters = {
    'BranchId':str, 
}

parse_dates = [
    'OpenDate',
    'RecordDate',
    'MaturityDate',
    'CloseDate',
    'BlockCode1Date',
    'OrigOpenDate',
    'Fecha_Cambio_Status',
    'Fecha_Reg_Venc_Lit_cast',
    'Fecha_Exigibilidad_pago_ult_cuota',
    'Fecha_Fin_Periodo_gracia_Pago_interes',
    'Fecha_cambio_Capital_Transferido'
]

In [4]:
siif = pd.read_csv('../vol/web/media/insumos/automatic/Reporte SIIF Final.txt', 
                   sep='	', 
                   low_memory=False, 
                   encoding = "latin",
                   parse_dates=parse_dates,
                   converters=converters,)

In [5]:
siif

,BranchId,Acct,OpenDate,DaysPastDue,RecordDate,MaturityDate,CreditLimit,Rate,NumPmtsPastDue,AmountPmtPastDue,Amt30DPD,Amt60DPD,Amt90DPD,Amt120DPD,Amt150DPD,Amt180DPD,Amt210DPD,LoanStatus,SaldoCastigado,CloseDate,BlockCodeId1,BlockReason1,BlockCode1Date,PrincipalBalance,TypeId,Gender,FullName,ActivityId,OccupationId,ProfessionId,RelId,DivisionTypeId,Agro,Micro,FondoEstadal,Rewrite,CtaLocal,Cid,Situacion_Credito,SaldoCapital,SaldoRendimientos,Mora,ClaseRiesgo,CantCuotasVencidas,EstadoCredito,OldAcct,OrigOpenDate,OrigCreditLimit,OrigTypeId,Staff,Purchases,FeePaid,Address,DireccionO,DireccionB,Int_Efectivamente_Cobrado,%Comsion_Flat,Monto_Comision_Flat,Periodicidad_Pago_Especial_Capital,Fecha_Cambio_Status,Fecha_Reg_Venc_Lit_cast,Fecha_Exigibilidad_pago_ult_cuota,Fecha_Fin_Periodo_gracia_Pago_interes,Capital_Trasferido,Fecha_cambio_Capital_Transferido,Tipo_Vivienda,Provision,SaldoProvision
0,,4487410000000658,2001-12-19,0,2019-06-30,NaT,Bs.S 0.00,0.34,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.04,2009-05-31,W,02,2010-11-29,Bs.S 0.04,999,F,"VELASQUEZ,LISMAR",607,1,32,NaN,C,0,0,0,0,8190310100,V11226138,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"AV. TAMANACO , EL L...",,,0.0,0.0,0.0,0,NaT,2010-11-29,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
1,,4487410000003199,2001-06-15,0,2019-06-30,NaT,Bs.S 0.00,0.29,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.02,2015-01-31,W,02,2015-05-02,Bs.S 0.02,999,F,"GAUNA DE BADUY,YOLANDA",614,1,10,NaN,C,0,0,0,0,8190310100,V4812738,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"CALLE MIRABAL , SECT...",,,0.0,0.0,0.0,0,NaT,2015-05-02,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
2,,4487410000004775,2001-05-12,0,2019-06-30,NaT,Bs.S 0.00,0.32,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.06,2017-01-31,W,02,2017-07-02,Bs.S 0.06,999,F,"JIMENEZ,ELAINE",604,1,27,NaN,C,0,0,0,0,8190310100,V5519507,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"AV LAZO MARTI , URB ...",,,0.0,0.0,0.0,0,NaT,2017-07-02,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
3,,4487410000006127,2001-09-10,0,2019-06-30,NaT,Bs.S 0.00,0.32,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.04,2009-11-30,W,02,2010-11-29,Bs.S 0.04,999,?,MIRIAM R. SILVA,620,1,2,NaN,C,0,0,0,0,8190310100,V4246202,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"CALLE LAS ORTENCIAS , TRIG...",,,0.0,0.0,0.0,0,NaT,2010-11-29,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
4,,4487410000008644,2001-11-21,0,2019-06-30,NaT,Bs.S 0.00,0.32,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.04,2011-12-31,W,02,2012-01-20,Bs.S 0.04,999,F,ANGELICA MARIA GOMEZ HERMAN,601,1,9,NaN,C,0,0,0,0,8190310100,V12821142,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"AV 5 DE JULIO , URB ...",,,0.0,0.0,0.0,0,NaT,2012-01-20,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15584,7,9017948801,2014-10-07,0,2019-06-30,2019-10-07,Bs.S 0.00,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.85,2016-11-30,NaN,NaN,NaT,Bs.S 0.00,16,M,"TREVOL SOLORZANO,RAFAEL ANTONIO",620,3,6,NaN,L,0,1,0,0,8190310400,V4904681,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"rmen Simon Bolivar , ...",,,0.0,0.0,0.0,0,NaT,2018-06-29,2014-10-08,1900-01-01,NaN,NaT,0,NaN,NaN
15585,7,9018086101,2014-07-08,0,2019-06-30,2019-07-08,Bs.S 0.00,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.23,2016-12-31,NaN,NaN,NaT,Bs.S 0.00,13,M,KENNY R RENDON T,601,1,10,NaN,L,0,0,0,0,8190310400,V14877745,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"al Puerto La Cruz Juan Antonio Sotillo, ...",,,0.0,0.0,0.0,0,NaT,2017-02-24,2014-07-09,1900-01-01,NaN,NaT,0,NaN,NaN
15586,7,9018209901,2014-10-09,0,2019-06-30,2019-10-09,Bs.S 0.00,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.29,2015-08-12,NaN,NaN,NaT,Bs.S 0.00,16,M,ENRIQUE F LAMAS E,612,3,1,NaN,L,0,1,0,0,8190310400,V8494776,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"RIAS TURISTICO DIEGO BAUT, ...",,,0.0,0.0,0.0,0,NaT,2017-07-31,2014-10-10,1900-01-01,NaN,NaT,0,NaN,NaN
15587,7,9019328801,2015-10-07,0,2019-06-30,2020-10-07,Bs.S 0.00,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.82,2016-12-31,NaN,NaN,NaT,Bs.S 0.00,13,F,HILDA E GONZALEZ R,627,1,7,NaN,L,0,0,0,0,8190310400,V4035366,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"may Caroni , ...",,,0.0,0.0,0.0,0,NaT,2017-02-24,2015-10-08,1900-01-01,NaN,NaT,0,NaN,NaN
15588,10,7033517801,1995-05-10,0,2019-06-30,NaT,Bs.S 0.00,0.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.07,2002-12-22,NaN,NaN,NaT,Bs.S 0.00,596,M,RAMON CAMPO MARTINEZ,601,1,4,NaN,R,0,0,0,0,8190310400,V3567523,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"CALLE P-1, URB. LA LAGUNITA, RES.JARDIN DE LA ...",,,0.0,0.0,0.0,0,NaT,2004-12-31,1995-05-11,1900-01-01,NaN,NaT,0,NaN,NaN

In [7]:
siif.CreditLimit.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt30DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt60DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt90DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt120DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt150DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt180DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.Amt210DPD.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.SaldoCastigado.replace(to_replace='Bs.S', value='', inplace=True, regex=True)
siif.PrincipalBalance.replace(to_replace='Bs.S', value='', inplace=True, regex=True)

siif.CreditLimit = pd.to_numeric(siif.CreditLimit, errors='coerce')
siif.Amt30DPD = pd.to_numeric(siif.Amt30DPD, errors='coerce')
siif.Amt60DPD = pd.to_numeric(siif.Amt60DPD, errors='coerce')
siif.Amt90DPD = pd.to_numeric(siif.Amt90DPD, errors='coerce')
siif.Amt120DPD = pd.to_numeric(siif.Amt120DPD, errors='coerce')
siif.Amt150DPD = pd.to_numeric(siif.Amt150DPD, errors='coerce')
siif.Amt180DPD = pd.to_numeric(siif.Amt180DPD, errors='coerce')
siif.Amt210DPD = pd.to_numeric(siif.Amt210DPD, errors='coerce')
siif.SaldoCastigado = pd.to_numeric(siif.SaldoCastigado, errors='coerce')
siif.PrincipalBalance = pd.to_numeric(siif.PrincipalBalance, errors='coerce')

In [9]:
siif

,BranchId,Acct,OpenDate,DaysPastDue,RecordDate,MaturityDate,CreditLimit,Rate,NumPmtsPastDue,AmountPmtPastDue,Amt30DPD,Amt60DPD,Amt90DPD,Amt120DPD,Amt150DPD,Amt180DPD,Amt210DPD,LoanStatus,SaldoCastigado,CloseDate,BlockCodeId1,BlockReason1,BlockCode1Date,PrincipalBalance,TypeId,Gender,FullName,ActivityId,OccupationId,ProfessionId,RelId,DivisionTypeId,Agro,Micro,FondoEstadal,Rewrite,CtaLocal,Cid,Situacion_Credito,SaldoCapital,SaldoRendimientos,Mora,ClaseRiesgo,CantCuotasVencidas,EstadoCredito,OldAcct,OrigOpenDate,OrigCreditLimit,OrigTypeId,Staff,Purchases,FeePaid,Address,DireccionO,DireccionB,Int_Efectivamente_Cobrado,%Comsion_Flat,Monto_Comision_Flat,Periodicidad_Pago_Especial_Capital,Fecha_Cambio_Status,Fecha_Reg_Venc_Lit_cast,Fecha_Exigibilidad_pago_ult_cuota,Fecha_Fin_Periodo_gracia_Pago_interes,Capital_Trasferido,Fecha_cambio_Capital_Transferido,Tipo_Vivienda,Provision,SaldoProvision
0,,4487410000000658,2001-12-19,0,2019-06-30,NaT,0.0,0.34,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,CUR,0.04,2009-05-31,W,02,2010-11-29,0.04,999,F,"VELASQUEZ,LISMAR",607,1,32,NaN,C,0,0,0,0,8190310100,V11226138,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"AV. TAMANACO , EL L...",,,0.0,0.0,0.0,0,NaT,2010-11-29,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
1,,4487410000003199,2001-06-15,0,2019-06-30,NaT,0.0,0.29,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,CUR,0.02,2015-01-31,W,02,2015-05-02,0.02,999,F,"GAUNA DE BADUY,YOLANDA",614,1,10,NaN,C,0,0,0,0,8190310100,V4812738,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"CALLE MIRABAL , SECT...",,,0.0,0.0,0.0,0,NaT,2015-05-02,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
2,,4487410000004775,2001-05-12,0,2019-06-30,NaT,0.0,0.32,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,CUR,0.06,2017-01-31,W,02,2017-07-02,0.06,999,F,"JIMENEZ,ELAINE",604,1,27,NaN,C,0,0,0,0,8190310100,V5519507,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"AV LAZO MARTI , URB ...",,,0.0,0.0,0.0,0,NaT,2017-07-02,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
3,,4487410000006127,2001-09-10,0,2019-06-30,NaT,0.0,0.32,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,CUR,0.04,2009-11-30,W,02,2010-11-29,0.04,999,?,MIRIAM R. SILVA,620,1,2,NaN,C,0,0,0,0,8190310100,V4246202,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"CALLE LAS ORTENCIAS , TRIG...",,,0.0,0.0,0.0,0,NaT,2010-11-29,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
4,,4487410000008644,2001-11-21,0,2019-06-30,NaT,0.0,0.32,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,CUR,0.04,2011-12-31,W,02,2012-01-20,0.04,999,F,ANGELICA MARIA GOMEZ HERMAN,601,1,9,NaN,C,0,0,0,0,8190310100,V12821142,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"AV 5 DE JULIO , URB ...",,,0.0,0.0,0.0,0,NaT,2012-01-20,2019-06-30,1900-01-01,NaN,NaT,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15584,7,9017948801,2014-10-07,0,2019-06-30,2019-10-07,0.0,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,0.85,2016-11-30,NaN,NaN,NaT,0.00,16,M,"TREVOL SOLORZANO,RAFAEL ANTONIO",620,3,6,NaN,L,0,1,0,0,8190310400,V4904681,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"rmen Simon Bolivar , ...",,,0.0,0.0,0.0,0,NaT,2018-06-29,2014-10-08,1900-01-01,NaN,NaT,0,NaN,NaN
15585,7,9018086101,2014-07-08,0,2019-06-30,2019-07-08,0.0,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,0.23,2016-12-31,NaN,NaN,NaT,0.00,13,M,KENNY R RENDON T,601,1,10,NaN,L,0,0,0,0,8190310400,V14877745,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"al Puerto La Cruz Juan Antonio Sotillo, ...",,,0.0,0.0,0.0,0,NaT,2017-02-24,2014-07-09,1900-01-01,NaN,NaT,0,NaN,NaN
15586,7,9018209901,2014-10-09,0,2019-06-30,2019-10-09,0.0,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,0.29,2015-08-12,NaN,NaN,NaT,0.00,16,M,ENRIQUE F LAMAS E,612,3,1,NaN,L,0,1,0,0,8190310400,V8494776,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"RIAS TURISTICO DIEGO BAUT, ...",,,0.0,0.0,0.0,0,NaT,2017-07-31,2014-10-10,1900-01-01,NaN,NaT,0,NaN,NaN
15587,7,9019328801,2015-10-07,0,2019-06-30,2020-10-07,0.0,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,0.82,2016-12-31,NaN,NaN,NaT,0.00,13,F,HILDA E GONZALEZ R,627,1,7,NaN,L,0,0,0,0,8190310400,V4035366,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"may Caroni , ...",,,0.0,0.0,0.0,0,NaT,2017-02-24,2015-10-08,1900-01-01,NaN,NaT,0,NaN,NaN
15588,10,7033517801,1995-05-10,0,2019-06-30,NaT,0.0,0.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,0.07,2002-12-22,NaN,NaN,NaT,0.00,596,M,RAMON CAMPO MARTINEZ,601,1,4,NaN,R,0,0,0,0,8190310400,V3567523,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaT,NaN,NaN,0,NaN,NaN,"CALLE P-1, URB. LA LAGUNITA, RES.JARDIN DE LA ...",,,0.0,0.0,0.0,0,NaT,2004-12-31,1995-05-11,1900-01-01,NaN,NaT,0,NaN,NaN

In [10]:
siif.to_csv('../vol/web/media/insumos/automatic/Reporte_SIIF_Final.txt', sep='~', date_format='%d/%m/%Y', index=False)