In [8]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_columns = 500
pd.options.display.max_rows = 10000

In [11]:
converters = {
    'BranchId':str, 
}

parse_dates = [
    'OpenDate',
    'RecordDate',
    'MaturityDate',
    'CloseDate',
    'BlockCode1Date',
    'OrigOpenDate',
    'Fecha_Cambio_Status',
    'Fecha_Reg_Venc_Lit_cast',
    'Fecha_Exigibilidad_pago_ult_cuota',
    'Fecha_Fin_Periodo_gracia_Pago_interes',
    'Fecha_cambio_Capital_Transferido'
]

In [12]:
siif = pd.read_csv('../vol/web/media/insumos/automatic/Reporte SIIF Final.txt', 
                   sep='	', 
                   low_memory=False, 
                   encoding = "latin",
                   parse_dates=parse_dates,
                   converters=converters,)

In [5]:
siif

,BranchId,Acct,OpenDate,DaysPastDue,RecordDate,MaturityDate,CreditLimit,Rate,NumPmtsPastDue,AmountPmtPastDue,Amt30DPD,Amt60DPD,Amt90DPD,Amt120DPD,Amt150DPD,Amt180DPD,Amt210DPD,LoanStatus,SaldoCastigado,CloseDate,BlockCodeId1,BlockReason1,BlockCode1Date,PrincipalBalance,TypeId,Gender,FullName,ActivityId,OccupationId,ProfessionId,RelId,DivisionTypeId,Agro,Micro,FondoEstadal,Rewrite,CtaLocal,Cid,Situacion_Credito,SaldoCapital,SaldoRendimientos,Mora,ClaseRiesgo,CantCuotasVencidas,EstadoCredito,OldAcct,OrigOpenDate,OrigCreditLimit,OrigTypeId,Staff,Purchases,FeePaid,Address,DireccionO,DireccionB,Int_Efectivamente_Cobrado,%Comsion_Flat,Monto_Comision_Flat,Periodicidad_Pago_Especial_Capital,Fecha_Cambio_Status,Fecha_Reg_Venc_Lit_cast,Fecha_Exigibilidad_pago_ult_cuota,Fecha_Fin_Periodo_gracia_Pago_interes,Capital_Trasferido,Fecha_cambio_Capital_Transferido,Tipo_Vivienda,Provision,SaldoProvision
0,NaN,4487410000000658,19/12/2001 00:00:00,0,30/6/2019 00:00:00,NaN,Bs.S 0.00,0.34,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.04,31/5/2009 00:00:00,W,02,29/11/2010 00:00:00,Bs.S 0.04,999,F,"VELASQUEZ,LISMAR",607,1,32,NaN,C,0,0,0,0,8190310100,V11226138,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"AV. TAMANACO , EL L...",,,0.0,0.0,0.0,0,NaN,29/11/2010 00:00:00,30/6/2019 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
1,NaN,4487410000003199,15/6/2001 00:00:00,0,30/6/2019 00:00:00,NaN,Bs.S 0.00,0.29,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.02,31/1/2015 00:00:00,W,02,5/2/2015 00:00:00,Bs.S 0.02,999,F,"GAUNA DE BADUY,YOLANDA",614,1,10,NaN,C,0,0,0,0,8190310100,V4812738,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"CALLE MIRABAL , SECT...",,,0.0,0.0,0.0,0,NaN,5/2/2015 00:00:00,30/6/2019 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
2,NaN,4487410000004775,5/12/2001 00:00:00,0,30/6/2019 00:00:00,NaN,Bs.S 0.00,0.32,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.06,31/1/2017 00:00:00,W,02,7/2/2017 00:00:00,Bs.S 0.06,999,F,"JIMENEZ,ELAINE",604,1,27,NaN,C,0,0,0,0,8190310100,V5519507,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"AV LAZO MARTI , URB ...",,,0.0,0.0,0.0,0,NaN,7/2/2017 00:00:00,30/6/2019 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
3,NaN,4487410000006127,9/10/2001 00:00:00,0,30/6/2019 00:00:00,NaN,Bs.S 0.00,0.32,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.04,30/11/2009 00:00:00,W,02,29/11/2010 00:00:00,Bs.S 0.04,999,?,MIRIAM R. SILVA,620,1,2,NaN,C,0,0,0,0,8190310100,V4246202,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"CALLE LAS ORTENCIAS , TRIG...",,,0.0,0.0,0.0,0,NaN,29/11/2010 00:00:00,30/6/2019 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
4,NaN,4487410000008644,21/11/2001 00:00:00,0,30/6/2019 00:00:00,NaN,Bs.S 0.00,0.32,NaN,NaN,NaN,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,Bs.S 0.00,CUR,Bs.S 0.04,31/12/2011 00:00:00,W,02,20/1/2012 00:00:00,Bs.S 0.04,999,F,ANGELICA MARIA GOMEZ HERMAN,601,1,9,NaN,C,0,0,0,0,8190310100,V12821142,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"AV 5 DE JULIO , URB ...",,,0.0,0.0,0.0,0,NaN,20/1/2012 00:00:00,30/6/2019 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15584,7.0,9017948801,10/7/2014 00:00:00,0,30/6/2019 00:00:00,10/7/2019 00:00:00,Bs.S 0.00,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.85,30/11/2016 00:00:00,NaN,NaN,NaN,Bs.S 0.00,16,M,"TREVOL SOLORZANO,RAFAEL ANTONIO",620,3,6,NaN,L,0,1,0,0,8190310400,V4904681,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"rmen Simon Bolivar , ...",,,0.0,0.0,0.0,0,NaN,29/6/2018 00:00:00,10/8/2014 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
15585,7.0,9018086101,7/8/2014 00:00:00,0,30/6/2019 00:00:00,7/8/2019 00:00:00,Bs.S 0.00,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.23,31/12/2016 00:00:00,NaN,NaN,NaN,Bs.S 0.00,13,M,KENNY R RENDON T,601,1,10,NaN,L,0,0,0,0,8190310400,V14877745,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"al Puerto La Cruz Juan Antonio Sotillo, ...",,,0.0,0.0,0.0,0,NaN,24/2/2017 00:00:00,7/9/2014 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
15586,7.0,9018209901,10/9/2014 00:00:00,0,30/6/2019 00:00:00,10/9/2019 00:00:00,Bs.S 0.00,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.29,8/12/2015 00:00:00,NaN,NaN,NaN,Bs.S 0.00,16,M,ENRIQUE F LAMAS E,612,3,1,NaN,L,0,1,0,0,8190310400,V8494776,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"RIAS TURISTICO DIEGO BAUT, ...",,,0.0,0.0,0.0,0,NaN,31/7/2017 00:00:00,10/10/2014 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
15587,7.0,9019328801,10/7/2015 00:00:00,0,30/6/2019 00:00:00,10/7/2020 00:00:00,Bs.S 0.00,0.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.82,31/12/2016 00:00:00,NaN,NaN,NaN,Bs.S 0.00,13,F,HILDA E GONZALEZ R,627,1,7,NaN,L,0,0,0,0,8190310400,V4035366,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"may Caroni , ...",,,0.0,0.0,0.0,0,NaN,24/2/2017 00:00:00,10/8/2015 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN
15588,10.0,7033517801,5/10/1995 00:00:00,0,30/6/2019 00:00:00,NaN,Bs.S 0.00,0.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAS,Bs.S 0.07,22/12/2002 00:00:00,NaN,NaN,NaN,Bs.S 0.00,596,M,RAMON CAMPO MARTINEZ,601,1,4,NaN,R,0,0,0,0,8190310400,V3567523,NaN,NaN,0,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,0,NaN,NaN,"CALLE P-1, URB. LA LAGUNITA, RES.JARDIN DE LA ...",,,0.0,0.0,0.0,0,NaN,31/12/2004 00:00:00,5/11/1995 00:00:00,1/1/1900 00:00:00,NaN,NaN,0,NaN,NaN

In [13]:
siif.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15589 entries, 0 to 15588
Data columns (total 68 columns):
BranchId                                 15589 non-null object
Acct                                     15589 non-null int64
OpenDate                                 15589 non-null datetime64[ns]
DaysPastDue                              15589 non-null int64
RecordDate                               15589 non-null datetime64[ns]
MaturityDate                             2718 non-null datetime64[ns]
CreditLimit                              15589 non-null object
Rate                                     15589 non-null float64
NumPmtsPastDue                           0 non-null float64
AmountPmtPastDue                         0 non-null float64
Amt30DPD                                 37 non-null object
Amt60DPD                                 8891 non-null object
Amt90DPD                                 8891 non-null object
Amt120DPD                                8891 non-null object
Amt150DPD                                8891 non-null object
Amt180DPD                                8891 non-null object
Amt210DPD                                8891 non-null object
LoanStatus                               15589 non-null object
SaldoCastigado                           14720 non-null object
CloseDate                                13899 non-null datetime64[ns]
BlockCodeId1                             8891 non-null object
BlockReason1                             8891 non-null object
BlockCode1Date                           8830 non-null datetime64[ns]
PrincipalBalance                         15589 non-null object
TypeId                                   15589 non-null int64
Gender                                   15589 non-null object
FullName                                 15589 non-null object
ActivityId                               15589 non-null int64
OccupationId                             15589 non-null int64
ProfessionId                             15589 non-null int64
RelId                                    1808 non-null object
DivisionTypeId                           15589 non-null object
Agro                                     15589 non-null int64
Micro                                    15589 non-null int64
FondoEstadal                             15589 non-null int64
Rewrite                                  15589 non-null int64
CtaLocal                                 15589 non-null int64
Cid                                      15589 non-null object
Situacion_Credito                        1808 non-null float64
SaldoCapital                             1808 non-null float64
SaldoRendimientos                        15589 non-null int64
Mora                                     228 non-null float64
ClaseRiesgo                              1808 non-null object
CantCuotasVencidas                       1808 non-null float64
EstadoCredito                            15589 non-null int64
OldAcct                                  38 non-null float64
OrigOpenDate                             38 non-null datetime64[ns]
OrigCreditLimit                          38 non-null object
OrigTypeId                               38 non-null float64
Staff                                    15589 non-null int64
Purchases                                370 non-null object
FeePaid                                  370 non-null object
Address                                  15526 non-null object
DireccionO                               15589 non-null object
DireccionB                               15589 non-null object
Int_Efectivamente_Cobrado                15589 non-null float64
%Comsion_Flat                            15589 non-null float64
Monto_Comision_Flat                      15589 non-null float64
Periodicidad_Pago_Especial_Capital       15589 non-null int64
Fecha_Cambio_Status                      23 non-null datetime64[ns]
Fecha_Reg_Venc_Lit_cast                  15589 non-null datetime64[ns]
Fecha_Exigibilidad_pago_ult_cuota        15589 non-null datetime64[ns]
Fecha_Fin_Periodo_gracia_Pago_interes    15589 non-null datetime64[ns]
Capital_Trasferido                       21 non-null float64
Fecha_cambio_Capital_Transferido         21 non-null datetime64[ns]
Tipo_Vivienda                            15589 non-null int64
Provision                                1808 non-null float64
SaldoProvision                           1808 non-null float64
dtypes: datetime64[ns](11), float64(15), int64(16), object(26)
memory usage: 8.1+ MB